### ISSUE TITLE
 Navbar Design and Alignment Issue – Improve UI Consistency

### ISSUE THREAD

**Issue by Ankul8471** [vishanurag/Canvas-Editor#1006]
Description: The current navbar on the Canvas Editor page needs refinement for a more cohesive look and better alignment. The spacing, colors, and layout could be optimized to enhance readability and visual appeal.

Proposed Solution:

Spacing Adjustments: Refine the margins and padding to make the navbar elements visually balanced.
Color Scheme Consistency: Ensure the colors match the overall theme for a cohesive design.
Alignment: Center-align the navbar items for a cleaner, more modern look.
Benefits:

Improved User Experience: A well-organized navbar helps users navigate effortlessly.
Enhanced Aesthetics: Consistent styling makes the interface visually appealing and professional.
![Screenshot 2024-10-28 140840](https://github.com/user-attachments/assets/97c40b30-f99f-4f7a-bf54-6a088e1f28fb)

**Comment by vishanurag** [comment]
similar issue is already assigned to someone else

**Comment by Ankul8471** [comment]
Ok sir if you want then I will also be ready to solve this

**Comment by vishanurag** [comment]
> Ok sir if you want then I will also be ready to solve this

You can work on other issues of this project

**Comment by Ankul8471** [comment]
ok
