### ISSUE TITLE
UI/UX Enhancement Needed for Consistent and User-Friendly Experience

### ISSUE THREAD

**Issue by Ankul8471** [vishanurag/Canvas-Editor#1007]
The current UI/UX of the Canvas Editor website could be improved for a smoother and more intuitive user experience. Some elements, such as spacing, font consistency, and color harmony, require attention to enhance the usability and visual appeal of the interface.

Proposed Improvements:

Consistent Spacing and Alignment: Adjust padding and margins across different sections to create a balanced layout.
Color Harmony: Align colors across elements for a cohesive look that’s easy on the eyes.
Improved Font Styling: Use a consistent font size and style to enhance readability and establish a clear visual hierarchy.
Additional Observations: In the attached video, certain transitions and animations seem abrupt, affecting the flow and user engagement.

Benefits:

Enhanced Visual Appeal: A polished interface creates a positive first impression and encourages engagement.
Improved Accessibility: Consistent fonts, colors, and layout make the website more accessible and enjoyable to use.

https://github.com/user-attachments/assets/88d588a0-8e72-4a27-8e91-e1f29a421a93

**Comment by Ankul8471** [comment]
@vishanurag please assign me this issue

**Comment by vishanurag** [comment]
similar issue is already assigned. refer https://github.com/vishanurag/Canvas-Editor/issues/1005
