### ISSUE TITLE
Creating Blog Page

### ISSUE THREAD

**Issue by Archisman141** [vishanurag/Canvas-Editor#101]
I want to create the blog  page. 

@vishanurag Please assign me this. Please add hacktober accepted label, gssoc-ext label.

**Comment by Archisman141** [comment]
@vishanurag blog page is added.....please check it and merge it

**Comment by Archisman141** [comment]
@vishanurag Sir I have created the blog page please check it and merge it

**Comment by Archisman141** [comment]
@vishanurag I have solved the conflict, now the PR is ready to get merged, Please check it and merge it

**Comment by vishanurag** [comment]
Closed via #291
