### ISSUE TITLE
Fixing home page implementation

### ISSUE THREAD

**Issue by Pallavi-Mukalla** [vishanurag/Canvas-Editor#1010]
The home page currently exhibits misalignment and a disorderly arrangement of items, negatively impacting user experience and overall aesthetics. Users have reported difficulty in navigating the page due to the inconsistent positioning of elements such as text, images, and buttons.
![Screenshot 2024-10-28 153916](https://github.com/user-attachments/assets/e0c57c0d-5472-4b17-b1cb-a0c01b4c9f82)
![Screenshot 2024-10-28 153941](https://github.com/user-attachments/assets/7bd05a0d-eecb-4aec-b7d9-d44ab446e5b4)

@vishanurag please assign me this issue

**Comment by vishanurag** [comment]
similar issue is already assigned. refer #1005
