### ISSUE TITLE
want to add a feedback form

### ISSUE THREAD

**Issue by srajangupta144** [vishanurag/Canvas-Editor#1019]
I would like to propose the addition of a feedback form to enhance user engagement and facilitate the collection of valuable insights from our community. A feedback form will empower users to share their experiences, suggestions, and any issues they may encounter while interacting with the project. This initiative is especially relevant under programs like GSSoC (GirlScript Summer of Code) and Hacktoberfest, which emphasize community participation and collaborative development.

Implementing a user-friendly feedback form will not only improve communication between users and maintainers but also help identify areas for enhancement within the project. By making it easy for users to voice their opinions and experiences, we can gain a clearer understanding of their needs and preferences. This feedback will serve as a critical resource for making informed decisions about future updates and features.

Moreover, providing users with a platform to express their thoughts will encourage a sense of ownership and investment in the project. This aligns with our commitment to continuous improvement and responsiveness to community input. I believe that this enhancement will significantly benefit both contributors and users, fostering a more vibrant and engaged community. Thank you for considering this important addition!

**Comment by vishanurag** [comment]
Similar issue already assigned to someone else
