### ISSUE TITLE
Fix UI of your webpage

### ISSUE THREAD

**Issue by srajangupta144** [vishanurag/Canvas-Editor#1020]
I would like to propose a comprehensive review and fix of the current user interface (UI) of our webpage to enhance the overall user experience. The existing UI may not align with modern design principles or best practices, which can lead to confusion and hinder user engagement. By addressing issues such as inconsistent styling, unresponsive elements, and unclear navigation, we can create a more intuitive and visually appealing interface.

A refined UI will not only improve aesthetics but also make it easier for users to navigate and access important features. Implementing design improvements, such as better color contrast, streamlined layouts, and responsive design elements, can significantly enhance usability across different devices and screen sizes. This initiative will foster a more positive interaction with our project, encouraging users to explore and utilize its full potential. I believe that prioritizing UI enhancements will lead to increased user satisfaction and engagement. Thank you for considering this important update!

**Comment by vishanurag** [comment]
Similar issue is already assigned to someone else
