### ISSUE TITLE
I want to improve styling, improve navbar

### ISSUE THREAD

**Issue by souvikpramanikgit** [vishanurag/Canvas-Editor#1026]
Here, you can see the chatbot is not in the right place, so i want to reposition this, also i want to add styling in navbar, as it is not looking well.

![image](https://github.com/user-attachments/assets/1b3bdfe4-c332-4658-bb19-2be273f5a461)

So assign me in this @vishanurag

**Comment by vishanurag** [comment]
You can change the position of chat bot. But navbar related issue is already assigned

**Comment by souvikpramanikgit** [comment]
ok thanks

**Comment by AsthaSingh22-8** [comment]
@vishanurag kindly assign me this issue.i want to work on it
