### ISSUE TITLE
Enhancement of SignUp Page : revamp the Signup Page for Improved User Experience

### ISSUE THREAD

**Issue by khushigupta86** [vishanurag/Canvas-Editor#1045]
The current layout and styling of the signup page could benefit from enhancements to improve user experience and overall visual appeal. Key areas of improvement include:

**UI Consistency:** Ensuring that elements align properly and are visually cohesive throughout the site.
Enhancements to improve the design and responsiveness of signup page, which require layout and visual improvements for a better user experience. By focusing on these areas, I aim to make the signup page more visually engaging and functional, aligning with the project goals in open-source programs like GSSoC and Hacktoberfest.

**Request:**
Please assign this issue to me and mark it at the highest level, as these improvements will take considerable time and effort to implement effectively.

![before s](https://github.com/user-attachments/assets/e03d9b15-53aa-4510-a76c-ec1a5dea5442)

**Comment by vishanurag** [comment]
Closed via #1071
