### ISSUE TITLE
Enhance the UI of the Login Page for a More Professional Look

### ISSUE THREAD

**Issue by itsHarsh2** [vishanurag/Canvas-Editor#1046]
DESCRIPTION  :
The current login page does not present a professional appearance, which may impact user trust and engagement. A redesign is needed to create a more polished and user-friendly interface.Description:

PROPOSED  ENHANCEMENT:

1. Overall Aesthetic :
  - Redesign the layout to create a clean, professional look that aligns with the brand identity.

2. Color Scheme :
  -  Update the color palette to use more cohesive and professional colors, ensuring good contrast for readability.

![WhatsApp Image 2024-10-29 at 00 11 38_fea607b5](https://github.com/user-attachments/assets/2aa98592-046e-426c-919e-bc72dc054c49)

**Comment by itsHarsh2** [comment]
Please assign it to me .I would like work on it.

**Comment by vishanurag** [comment]
Similar issue is already assigned to someone else
