### ISSUE TITLE
[BUG] Duplicate navbar

### ISSUE THREAD

**Issue by shreya2k3** [vishanurag/Canvas-Editor#1049]
### Description

There are two navbars on the home page, one on the top and one at bottom of screenshot attached.

### Screenshots

![image](https://github.com/user-attachments/assets/f40f4a7d-7e0a-4f8c-bf58-cd4a3ff29381)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/alo7lika/Canvas-Editor/blob/dev/Contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by shreya2k3** [comment]
@vishanurag pls assign the issue to me

**Comment by vishanurag** [comment]
Issue already resolved
