### ISSUE TITLE
🧑‍💻: Enhance Login Page UI by Updating Font Color for Better User Experience

### ISSUE THREAD

**Issue by shreya5653** [vishanurag/Canvas-Editor#1054]
### Title

Enhance Login Page UI by Updating Font Color for Better User Experience

### Enhancement Aim

The aim of this issue is to improve the readability and visual appeal of the login page by changing the font color. Enhancing the contrast between the text and background will ensure that users can clearly see and interact with the login elements, resulting in a more accessible and user-friendly experience.

### Changes

To change font color 

### Screenshots 📷

![Screenshot (133)](https://github.com/user-attachments/assets/0757621d-e34c-4a20-b33a-e65b0a865e5b)

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Shreya Kore

### Participant Role

GSSOC EXTENDED Contributor / Hacktoberfest Contributor

**Comment by shreya5653** [comment]
@vishanurag I want to work on this issue please assign it to me

**Comment by vishanurag** [comment]
Closed via #1063

**Comment by vishanurag** [comment]
Closed via #1063
