### ISSUE TITLE
UI Enhancement: Improve Homepage Layout and Navigation

### ISSUE THREAD

**Issue by Aman-G-upta** [vishanurag/Canvas-Editor#1095]
The current design of the Canvas Editor homepage could be enhanced to improve usability and overall visual appeal. This includes several UI adjustments such as adding a website icon, reorganizing the navigation bar, adjusting colors, and aligning elements consistently.

Add a Favicon (Website Icon):
Include a recognizable icon for the website in the browser tab to improve branding and make it easily identifiable.

Navigation Bar Improvements:
Enhance the color contrast of the navigation bar for better readability.
Adjust button sizes and spacing for a cleaner layout.
Consider adding hover effects for navigation links to improve interactivity.

Button Styling and Alignment:
Style action buttons (like Pencil, Marker, Eraser) for a modern look and ensure they are evenly spaced.
Add tooltips for each button so users can quickly understand each option.

Footer Enhancements:
Improve the footer section design by increasing color contrast and centering the elements.
Add social media icons or other links as relevant to enhance footer functionality.

![Screenshot 2024-10-29 222558](https://github.com/user-attachments/assets/7e2f70f2-21a5-489f-9cc2-e5345989edb5)

**Comment by vishanurag** [comment]
Go ahead but remember navbar related issue is already assigned to someone else. You can work on homepage layout only

**Comment by vishanurag** [comment]
Closed via #1115
