### ISSUE TITLE
Center Signup Form in signup  page

### ISSUE THREAD

**Issue by Raj-banerjee25** [vishanurag/Canvas-Editor#1096]
### Description

the signup form is positioned in the corner of the page, while the navbar is centered. This creates a visual inconsistency, making the layout appear unbalanced. Centering the signup form will improve the overall user interface by aligning key elements uniformly on the page.

### Screenshots

![edit6](https://github.com/user-attachments/assets/2d7c8922-ea4d-40cd-b975-b97e817eca0c)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/alo7lika/Canvas-Editor/blob/dev/Contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by vishanurag** [comment]
Similar issue is already assigned to someone else
