### ISSUE TITLE
Fonstyle and Box-border and background color

### ISSUE THREAD

**Issue by KAmaL-senpai** [vishanurag/Canvas-Editor#11]
I can help to modify the th Fonsstyle , background color and box-border making this editor more visual appealing assign this to me

**Comment by Ibrangrd** [comment]
I would like to work on this.
Would you assign it to me under GSSoC24 extd and hacktoberfest24?
Thank you.

**Comment by vishanurag** [comment]
> I would like to work on this. Would you assign it to me under GSSoC24 extd and hacktoberfest24? Thank you.

This issue has been assigned.
You can create a new issue

**Comment by rounakdey6** [comment]
i want to work on this issue
