### ISSUE TITLE
[BUG] : Toggle grid button is not appropriate

### ISSUE THREAD

**Issue by VanshGarg06** [vishanurag/Canvas-Editor#1101]
### Description

The toggle Grid Button alignment is not appropriate and it is consuming the whole viewport height which is not necessary and could be placed with other necessary buttons. This is not good as User Interface of the website and the user experience also degrades as the size is very large.

### Screenshots

![image](https://github.com/user-attachments/assets/f3928fd5-1ef1-45e9-b6eb-06c0d1cf0837)

### Any additional information?

@vishanurag Please assign this task to me @VanshGarg06 under hacktoberfest and gssoc-ext with the necessary labels of level 2. Please assign this task to me as soon as possible so as I can make pull requests timely and merge requests.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/alo7lika/Canvas-Editor/blob/dev/Contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by vishanurag** [comment]
Already resolved
