### ISSUE TITLE
🧑‍💻: UI Enhancement of the Navbar header

### ISSUE THREAD

**Issue by VanshGarg06** [vishanurag/Canvas-Editor#1102]
### Title

UI Enhancement of the Navbar of the Website

### Enhancement Aim

The User Interface of the Navbar needs enhancement as it is just a simple looking navbar and styling of the same will increase the user experience as well as Navbar is an important part of any website and its styling is a must.

### Changes

1. Styling of Header 
2. Styling of Navbar
3. Styling of the Name in Header

### Screenshots 📷

![image](https://github.com/user-attachments/assets/1960f4db-8591-4cac-bf6c-3589772581c1)

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Vansh Garg(Github username: @VanshGarg06 )

### Participant Role

GSSOC-EXT
Hacktoberfest

**Comment by vishanurag** [comment]
Similar issue is already assigned to someone else
