### ISSUE TITLE
Features: Sign Up and login page

### ISSUE THREAD

**Issue by Lekkhasri** [vishanurag/Canvas-Editor#112]
Improving the Website:
                                    By adding the Sign Up and Login option . The user can save their work , when ever they want to view their work by login they can view it and the new user can sign up and look their work. 
This will help the user more. I like to work on this  can you assign it to me.

**Comment by Shruti2183** [comment]
@vishanurag i would like to work if @Lekkhasri is not working on this issue!

**Comment by Lekkhasri** [comment]
@Shruti2183 i am currently working in this issue

**Comment by vishanurag** [comment]
Closed via #176
