### ISSUE TITLE
Feat: Adding a custom Preloader

### ISSUE THREAD

**Issue by Peart-Guy** [vishanurag/Canvas-Editor#1126]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I want to add a custom preloader which matches the theme and aesthetic of the website

I have provided a sample video. The final product may vary depending on your specific needs and preferences. I look forward to the opportunity to contribute to your project .

### Add ScreenShots

https://github.com/user-attachments/assets/c304be59-6409-4cc4-8d6a-8adde44c4e4c

### Component

Before the website loads

### It should be implemented because

It enhances the beauty of the project and show that there have been efforts made behind this projects

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by Peart-Guy** [comment]
@vishanurag Kindly assign me this issue

**Comment by vishanurag** [comment]
The similar issue is already assigned to someone else
