### ISSUE TITLE
button size is not good 

### ISSUE THREAD

**Issue by siddhant-2002** [vishanurag/Canvas-Editor#1131]
### Issue Summary

buttons for usage and settings is not proparly designed

### Issue Description

design of buttons is not proper

### Proposed Solution (Optional)

![image](https://github.com/user-attachments/assets/5955aabe-397f-4dc1-b10f-a710eee066e6)

### Priority

High - Requires urgent attention

### Category

- [X] Enhancement
- [ ] Refactor
- [ ] Security
- [X] Design
- [ ] Other

**Comment by vishanurag** [comment]
Similar issue is already assigned to someone else
