### ISSUE TITLE
[BUG] View Passwords dash eye icon 

### ISSUE THREAD

**Issue by PATILYASHH** [vishanurag/Canvas-Editor#1134]
### Description

when user want to see password and user clicked on eye icon then password is visible but not dash eye icon is available . dash eye icon will improve the user experience 

### Screenshots

https://github.com/user-attachments/assets/ce868cea-dc4e-47b4-a535-7c6c4cb2f243

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/alo7lika/Canvas-Editor/blob/dev/Contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by PATILYASHH** [comment]
can you replace 1st level label with 2nd level

**Comment by PATILYASHH** [comment]
sir can you replace 1st level label with 2nd level because my exams are going to start and I am trying to gain much points I can

**Comment by vishanurag** [comment]
> sir can you replace 1st level label with 2nd level because my exams are going to start and I am trying to gain much points I can

Brother my exams are also going to start from Monday 😅

**Comment by PATILYASHH** [comment]
😅

**Comment by PATILYASHH** [comment]
I did PR please review it
