### ISSUE TITLE
Feat:Navbar design 

### ISSUE THREAD

**Issue by Aditya90456** [vishanurag/Canvas-Editor#1140]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

improve navbar design 

### Add ScreenShots

![Med-Space _ Efficient Healthcare Appointments   Queue Management and 4 more pages - Personal 2 - Microsoft​ Edge Beta 11_1_2024 1_53_52 PM](https://github.com/user-attachments/assets/8a43d6ce-0192-4834-9718-7fc41cca9f27)

### Component

/navbar

### It should be implemented because

I use css implement 

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by vishanurag** [comment]
Similar issue is already assigned to someone else
