### ISSUE TITLE
Feat: Add a User Profiles page 🌟🌟🌟

### ISSUE THREAD

**Issue by Subhajit-2023-44** [vishanurag/Canvas-Editor#1143]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

👤✨ I want to create a normal user profile page and a profile icon in the home page navbar that redirects to the profile page...

PA please assign me for this task...

### Add ScreenShots

.

### Component

.

### It should be implemented because

.

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by Subhajit-2023-44** [comment]
@vishanurag @somyadipghosh

**Comment by vishanurag** [comment]
I don't think this feature is needed for this project

**Comment by Subhajit-2023-44** [comment]
> I don't think this feature is needed for this project

@vishanurag sir of course its totally your choice but sir i think every website at least needs a simple user profile page for those who have login/signup feature.. if u agree please assign me sir..

I want to create a normal user profile page and a profile icon in the home page navbar that redirects to the profile page...

**Comment by Subhajit-2023-44** [comment]
@vishanurag sir open this assign request

**Comment by vishanurag** [comment]
closed via #1181
