### ISSUE TITLE
[BUG] Login with microsoft, google and github buttons are not functional

### ISSUE THREAD

**Issue by sania-2912** [vishanurag/Canvas-Editor#1162]
### Description

Currently, the "Sign in with Microsoft," "Sign in with Google," and "Sign in with GitHub" buttons are present on the login page as placeholders. However, they are not yet functional, meaning users cannot log in using these options. This issue exists because the necessary integrations with Microsoft, Google, and GitHub authentication services have not been fully set up.

Implementing these features requires configuring OAuth or OpenID Connect protocols, creating app registrations with each provider, and handling authentication tokens securely within our platform. Addressing this will provide users with convenient, single-click login options, enhancing the user experience. 

### Screenshots

https://github.com/user-attachments/assets/063aefa5-350a-439a-aa96-924e988e92b9

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/alo7lika/Canvas-Editor/blob/dev/Contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by sania-2912** [comment]
@vishanurag kindly assign this issue to me.

**Comment by sania-2912** [comment]
@vishanurag kindly initiate the first PR. This page is done as well and i will create a PR for this one then

**Comment by vishanurag** [comment]
closed via #1198
