### ISSUE TITLE
🧑‍💻: Improve color theme

### ISSUE THREAD

**Issue by Anushkam09** [vishanurag/Canvas-Editor#1167]
### Title

Improve color theme

### Enhancement Aim

To enhance the website visually as the current color theme does not suit the eyes well.

### Changes

Change the dark blue color into a better shade of blue

### Screenshots 📷

![image](https://github.com/user-attachments/assets/e0287d0c-43ca-4cca-9371-3ab934bd5a99)

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Full Name

Anushka Mahajan

### Participant Role

Contributor

**Comment by Harshini4080** [comment]
please assign me this task under gssoc 24 and with hacktoberfest label

**Comment by vishanurag** [comment]
Similar issue is already assigned to someone-else
