### ISSUE TITLE
🧑‍💻: Enhancing the entire user interface of the feedback section by giving it an elegant color theme. 

### ISSUE THREAD

**Issue by shriyadindi** [vishanurag/Canvas-Editor#1176]
### Title

Enhancing the entire user interface of the feedback section by giving it an elegant color theme. 

### Enhancement Aim

Enhancing the entire user interface of the feedback section by giving it an elegant color theme. 

### Changes

Enhancing the entire user interface of the feedback section by giving it an elegant color theme. 

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Shriya 

### Participant Role

GSSOC

**Comment by vishanurag** [comment]
Issue already resolved
