### ISSUE TITLE
🧑‍💻: Improve Ui of Home page 

### ISSUE THREAD

**Issue by falak412** [vishanurag/Canvas-Editor#1192]
### Title

Improvement in ui of home page and navbar.

### Enhancement Aim

to make website more attractive and according to the theme.

### Changes

improvement in home page and making buttons in proper shape and background.  improvement in navbar by defining separate buttons. 

### Screenshots 📷

![Screenshot (107)](https://github.com/user-attachments/assets/f04e67b6-8297-417c-9c32-037ad649f900)

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Falak Vhora

### Participant Role

GSSoC'24 Extd Contributor

**Comment by vishanurag** [comment]
Similar issue is already assigned to someone else
