### ISSUE TITLE
[BUG] fix the cursor animation, check description 

### ISSUE THREAD

**Issue by AE-Hertz** [vishanurag/Canvas-Editor#1194]
### Description

the cursor animation is still visible even after user's cursor is moved to another display or not at the site,

Expected ;
the cursor animation should disapper if the user's cursor is not on the site.

I will fix this issue. Assign me this.

### Screenshots

![Screenshot 2024-11-04 212338](https://github.com/user-attachments/assets/8581e093-f930-4641-8ca9-ad6a92a05d8d)

### What browser are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/alo7lika/Canvas-Editor/blob/dev/Contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by AE-Hertz** [comment]
@vishanurag can you assign me this issue.

**Comment by vijay0984567** [comment]
can i start working upon it? Assign me this task
