### ISSUE TITLE
Feat: Add Project Statistics in Contributors page

### ISSUE THREAD

**Issue by Subhajit-2023-44** [vishanurag/Canvas-Editor#1203]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I want to add a Project Statistics section in Contributors page..

Please assign me

![image](https://github.com/user-attachments/assets/6ce71a04-f3de-4203-aae1-a2fd0bd1cdf9)

### Add ScreenShots

.

### Component

.

### It should be implemented because

.

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by Subhajit-2023-44** [comment]
@vishanurag

**Comment by vishanurag** [comment]
closed via #1218
