### ISSUE TITLE
🧑‍💻: change theme of FAQ page to as of other pages

### ISSUE THREAD

**Issue by Kajalmehta29** [vishanurag/Canvas-Editor#1206]
### Title

Improve the color theme of FAQ page

### Enhancement Aim

THis will look your website look more systematic and attractive if the color theme of all pages will be same

### Changes

Change background color and color of theory written

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Full Name

Kajal Mehta

### Participant Role

GSSOC, Hacktoberfest.

**Comment by vishanurag** [comment]
Issue is already resolved
