### ISSUE TITLE
Redeisgn Community page of the project 

### ISSUE THREAD

**Issue by SIYAPARI** [vishanurag/Canvas-Editor#1209]
Issue :
i wish to redesign community page , because the navbar does not look so appealing  as well the overall color theme of page is also not matching with rest of the elements on the page   ,  i would try to add some smooth transitions on the members card , i would like to work on that part and thus make the page look more attractive.

Screenshots :
![image](https://github.com/user-attachments/assets/a57d7b60-117e-4aa6-902b-17156135fc9d)

Role:
Gssoc'24 extended contibutor

**Comment by SIYAPARI** [comment]
![image](https://github.com/user-attachments/assets/970b169c-7570-4d2d-b48a-399ecb983d5f)
I am getting this error while pushing code to branch

**Comment by vishanurag** [comment]
> [SIYAPARI](/SIYAPARI)

Most probably you are trying to push your code in vishanurag/Canvas-Editor not on the forked repo. You have to push your code to the forked repo of the original one.
Firstly, clone the latest forked repo code in your computer then make changes on it then push it.

**Comment by SIYAPARI** [comment]
> > @vishanurag ![image](https://private-user-images.githubusercontent.com/178636094/384624959-970b169c-7570-4d2d-b48a-399ecb983d5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNzExMTIsIm5iZiI6MTczMTE3MDgxMiwicGF0aCI6Ii8xNzg2MzYwOTQvMzg0NjI0OTU5LTk3MGIxNjljLTc1NzAtNGQyZC1iNDhhLTM5OWVjYjk4M2Q1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxNjQ2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2U2MWM3NTc4ZThiOGNiMzFlOWU4ZTYwZTE5MWZjZmNkMmI5NWQyZmM4Yzc2MzVmODA5MDUxMDM5MTMxYWVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cLY1Q1A8ovBy-fLuT6hmXQXoijJjf5z2w6Y2upucO8k) I am getting this error while pushing code to branch
> 
> @SIYAPARI
> 
> Most probably you are trying to push your code in vishanurag/Canvas-Editor not on the forked repo. You have to push your code to the forked repo of the original one. Firstly, clone the latest forked repo code in your computer then make changes on it then push it.

@vishanurag  Will i have to fork again ?

**Comment by vishanurag** [comment]
> > > @vishanurag ![image](https://private-user-images.githubusercontent.com/178636094/384624959-970b169c-7570-4d2d-b48a-399ecb983d5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNzExMTIsIm5iZiI6MTczMTE3MDgxMiwicGF0aCI6Ii8xNzg2MzYwOTQvMzg0NjI0OTU5LTk3MGIxNjljLTc1NzAtNGQyZC1iNDhhLTM5OWVjYjk4M2Q1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxNjQ2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2U2MWM3NTc4ZThiOGNiMzFlOWU4ZTYwZTE5MWZjZmNkMmI5NWQyZmM4Yzc2MzVmODA5MDUxMDM5MTMxYWVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cLY1Q1A8ovBy-fLuT6hmXQXoijJjf5z2w6Y2upucO8k) I am getting this error while pushing code to branch
> > 
> > 
> > @SIYAPARI
> > Most probably you are trying to push your code in vishanurag/Canvas-Editor not on the forked repo. You have to push your code to the forked repo of the original one. Firstly, clone the latest forked repo code in your computer then make changes on it then push it.
> 
> @vishanurag Will i have to fork again ?

If you have already forked then don't need to fork.
You just need to clone/pull that forked repo in your local machine and then make your code changes. After that you will be able to push the code to github. Then simply create a PR.

**Comment by SIYAPARI** [comment]
> > > > @vishanurag ![image](https://private-user-images.githubusercontent.com/178636094/384624959-970b169c-7570-4d2d-b48a-399ecb983d5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNzExMTIsIm5iZiI6MTczMTE3MDgxMiwicGF0aCI6Ii8xNzg2MzYwOTQvMzg0NjI0OTU5LTk3MGIxNjljLTc1NzAtNGQyZC1iNDhhLTM5OWVjYjk4M2Q1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxNjQ2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2U2MWM3NTc4ZThiOGNiMzFlOWU4ZTYwZTE5MWZjZmNkMmI5NWQyZmM4Yzc2MzVmODA5MDUxMDM5MTMxYWVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cLY1Q1A8ovBy-fLuT6hmXQXoijJjf5z2w6Y2upucO8k) I am getting this error while pushing code to branch
> > > 
> > > 
> > > @SIYAPARI
> > > Most probably you are trying to push your code in vishanurag/Canvas-Editor not on the forked repo. You have to push your code to the forked repo of the original one. Firstly, clone the latest forked repo code in your computer then make changes on it then push it.
> > 
> > 
> > @vishanurag Will i have to fork again ?
> 
> If you have already forked then don't need to fork. You just need to clone/pull that forked repo in your local machine and then make your code changes. After that you will be able to push the code to github. Then simply create a PR.

@vishanurag i had done the same steps ,
first i cloned , then i created branch ,then i added upstream , then changed locally , add , commit and while pushing i get this error

**Comment by SIYAPARI** [comment]
> 

and when i try to push to my forked repo , this is the error i get 
![image](https://github.com/user-attachments/assets/9e5cda99-3445-43f4-99a9-8c1a7340cc4f)

**Comment by vishanurag** [comment]
Try to run following command:

 - `git push -u origin main`

**Comment by SIYAPARI** [comment]
> Try to run following command:
> 
> * `git push -u origin main`
![image](https://github.com/user-attachments/assets/acaed0bf-f478-4336-845b-e88869420f66)

**Comment by vishanurag** [comment]
> > Try to run following command:
> > 
> > * `git push -u origin main`
> >   ![image](https://private-user-images.githubusercontent.com/178636094/384627491-acaed0bf-f478-4336-845b-e88869420f66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNzMyOTUsIm5iZiI6MTczMTE3Mjk5NSwicGF0aCI6Ii8xNzg2MzYwOTQvMzg0NjI3NDkxLWFjYWVkMGJmLWY0NzgtNDMzNi04NDViLWU4ODg2OTQyMGY2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxNzIzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjdiZmQ5NmQ0YzgzNGJiZjhjZTQyZDA4NjQyY2Y4MDViZDVjYmEyMTI3N2RmYTViMzY1ZjUzMmEzNTUxNGQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MS29X7HKkh4-e-9TB4uE2472p5e2HQdsnjMZt7fH4X0)

Don't add upstream 
just clone, make code changes, then push via this command `git push -u origin main`

**Comment by SIYAPARI** [comment]
> You don't need to add upstream because you have to push your code to forked repo first not to the original one.

ok let me try

**Comment by SIYAPARI** [comment]
> git push -u origin main

![image](https://github.com/user-attachments/assets/b8a9f2bd-8348-4307-b8e5-8849311f2c60)
See pls

**Comment by vishanurag** [comment]
Try running:

`git checkout -b new-branch`
`git push -u origin new-branch`

**Comment by vishanurag** [comment]
> > Try running:
> > `git checkout -b new-branch` `git push -u origin new-branch`
> 
> i had to create branch too ?

yes

**Comment by SIYAPARI** [comment]
ok so , clone ,make branch , do changes( add , commit ) , then push
Right?

**Comment by vishanurag** [comment]
> ok so , clone ,make branch , do changes( add , commit ) , then push Right?

yes

**Comment by SIYAPARI** [comment]
> > ok so , clone ,make branch , do changes( add , commit ) , then push Right?
> 
> yes

ok

**Comment by SIYAPARI** [comment]
> > > ok so , clone ,make branch , do changes( add , commit ) , then push Right?
> > 
> > 
> > yes
> 
> ok

@vishanurag just confirm where to push ?
