### ISSUE TITLE
Feat: Add Edit Profile Feature in Profile Page 🟢

### ISSUE THREAD

**Issue by Subhajit-2023-44** [vishanurag/Canvas-Editor#1214]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I want to add a Edit Profile Feature in Profile Page ✨✨

🟢Users can personalize their experience. They can update their name, profile image (avatar), email, phone number, bio.. to make the profile more reflective of their preferences. A user will feel more connected to the platform if they can customize their profile to reflect their personality or interests..

PA please assign me for this task..

### Add ScreenShots

.

### Component

.

### It should be implemented because

.

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by Subhajit-2023-44** [comment]
@vishanurag sir please assign me with level 3

**Comment by vishanurag** [comment]
closed via #1247
