### ISSUE TITLE
Feat:Uniform footer to the entire website

### ISSUE THREAD

**Issue by likitha-kapu** [vishanurag/Canvas-Editor#1229]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

There is no uniformity in footer section of the website.
![image](https://github.com/user-attachments/assets/824a9a06-b0c3-4410-981c-68a1df993409)

### Add ScreenShots

![Screenshot 2024-11-09 154046](https://github.com/user-attachments/assets/cde59df6-7dea-4a47-9b6f-946b54bf989f)

### Component

adding a footer to all the pages

### It should be implemented because

To have a uniformity in the website

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by likitha-kapu** [comment]
@vishanurag assign me this task...I wish to work on it

**Comment by likitha-kapu** [comment]
@vishanurag Is this ok ?
![image](https://github.com/user-attachments/assets/3e62316f-e4b8-44f4-9e75-c61a752e01b9)

**Comment by vishanurag** [comment]
> @vishanurag Is this ok ? ![image](https://private-user-images.githubusercontent.com/172056443/384625947-3e62316f-e4b8-44f4-9e75-c61a752e01b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNzE5NTQsIm5iZiI6MTczMTE3MTY1NCwicGF0aCI6Ii8xNzIwNTY0NDMvMzg0NjI1OTQ3LTNlNjIzMTZmLWU0YjgtNDRmNC05ZTc1LWM2MWE3NTJlMDFiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxNzAwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTlhNzJhMjJlYzM3MDdhYzNhYmU1ZTIxYTM3YmE5OTM1ZTlkN2U3NDIwMjIzM2I1YjFmODljZDhiMDBjMWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xl6aNuT7zyf1l5PWD-g0qcgB3ThQqeqjDMIhQmbEcEM)

Yes. It looks good. But make sure that the LinkedIn icon of footer redirects to: https://www.linkedin.com/in/anuragvishwakarma/
