### ISSUE TITLE
🐛[BUG] : Mouse animation  missing and some more error on About Us page 

### ISSUE THREAD

**Issue by akash70629** [vishanurag/Canvas-Editor#1240]
### Description

Mouse animation is missing on About us page and some more errors are there like heading misplace.

### Screenshots

https://github.com/user-attachments/assets/23a05752-3f16-499c-9796-28893b27bd17

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/alo7lika/Canvas-Editor/blob/dev/Contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by akash70629** [comment]
@vishanurag please assign me this issue .

**Comment by vishanurag** [comment]
> @vishanurag please assign me this issue .

done
