### ISSUE TITLE
[BUG] Remove duplicate login/sign up page button

### ISSUE THREAD

**Issue by Subhajit-2023-44** [vishanurag/Canvas-Editor#1269]
### Description

I want to remove duplicate login/sign up page button/icon...

![Screenshot 2024-11-10 021655](https://github.com/user-attachments/assets/8fbbd74a-1edd-4eb0-b70e-f3c51dd8362f)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/alo7lika/Canvas-Editor/blob/dev/Contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by vishanurag** [comment]
Closed via #1270
