### ISSUE TITLE
[BUG] Header misalignment in Tutorial page 🐞🐞🐞

### ISSUE THREAD

**Issue by Subhajit-2023-44** [vishanurag/Canvas-Editor#1271]
### Description

Header misalignment in Tutorial page , I want to fixed this issue properly....

![Screenshot 2024-11-10 025039](https://github.com/user-attachments/assets/417c81c5-9fbd-44c0-8137-37b4f843dd3a)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/alo7lika/Canvas-Editor/blob/dev/Contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by vishanurag** [comment]
Closed via #1272
