### ISSUE TITLE
[BUG] Add same header in all page 

### ISSUE THREAD

**Issue by Subhajit-2023-44** [vishanurag/Canvas-Editor#1275]
### Description

All page have different header which doesn't look beautiful, i want to add same header in all page...

https://github.com/user-attachments/assets/16369d64-6bc4-4868-b4c5-6720ced51a7b

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/alo7lika/Canvas-Editor/blob/dev/Contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by vishanurag** [comment]
Closed via #1276
