### ISSUE TITLE
🐛[BUG] :  Happy Clients count is static 

### ISSUE THREAD

**Issue by akash70629** [vishanurag/Canvas-Editor#1277]
### Description

Happy Clients count is static, It should show the exact number like a genuine website .

### Screenshots

![image](https://github.com/user-attachments/assets/0e47093c-96fe-4fad-b7b6-23b0317ff40b)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/alo7lika/Canvas-Editor/blob/dev/Contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by akash70629** [comment]
@vishanurag Please assign me this issue.

**Comment by vishanurag** [comment]
Closed via #1279
