### ISSUE TITLE
🧑‍💻: Privacy policy page mobile responsiveness

### ISSUE THREAD

**Issue by SimonNungwa** [vishanurag/Canvas-Editor#1288]
### Title

Request to fix mobile responsiveness

### Enhancement Aim

I noticed the view on mobile is not responsive

### Changes

I want to remove page overflow to allow the page fit to the viewport and implement a responsive navbar 

### Screenshots 📷

![pageRes](https://github.com/user-attachments/assets/6569e997-4de9-4d59-a5f0-1c6866b2ffce)

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Simon Nungwa

### Participant Role

I do not have one

**Comment by vishanurag** [comment]
Sure! I'm assigning this issue to you.

**Comment by SimonNungwa** [comment]
Alright i'll fork it right away

**Comment by vishanurag** [comment]
Closed via PR #1289

**Comment by SimonNungwa** [comment]
This is a project that I will like to actively contribute to. I'll raise other issues like new features for the editor and responsivesness across the site.

**Comment by vishanurag** [comment]
> This is a project that I will like to actively contribute to. I'll raise other issues like new features for the editor and responsivesness across the site.

Yea Sure 👍
Happy to work with you 😊
