### ISSUE TITLE
To add background to canvas 

### ISSUE THREAD

**Issue by gayu999Code** [vishanurag/Canvas-Editor#13]
Just like notes in the mobile phone has background options also google chrome also has theme option , likewise if we can add the background feature to our canvas .

I would like to contribute / work on this 
![Canvas-editor-feature-1](https://github.com/user-attachments/assets/f82e3883-3d33-4c56-a584-1ec3e45b811c)
![Canvas-editor-feature-2](https://github.com/user-attachments/assets/09c745e5-fb4f-4628-8350-dfdc2a4a0583)
![Canvas-editor-feature-3](https://github.com/user-attachments/assets/a333b229-8212-4d8b-af5c-5ba588d87a87)

**Comment by vishanurag** [comment]
Great idea 💡.
I'm assigning this issue to you.

**Comment by gayu999Code** [comment]
Yeah I am working on it @vishanurag
