### ISSUE TITLE
Contact us section is not visually appealing

### ISSUE THREAD

**Issue by hariscoder3** [vishanurag/Canvas-Editor#131]
The contact us section of website is not visually appealing, I can work on this, kindly assign me this issue under gssoc-ext, hacktoberfest-accepted and level2. 
![contact_us_page](https://github.com/user-attachments/assets/4fd61860-b031-47f8-9fa7-eb719501f081)

**Comment by PREM-A261** [comment]
![image](https://github.com/user-attachments/assets/b9f6c03a-1d47-43c9-823e-75615cf90b22)
 how it look now 
@PREM-A261 Please assign me this task i will make it neat ,clear and functional.

**Comment by hariscoder3** [comment]
@PREM-A261 I have done the pull request, once it is accepted, you can see the updated website, now which you can see is not updated!
