### ISSUE TITLE
Contributing.md not linked in README.md file.

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [vishanurag/Canvas-Editor#133]
**README.md**:
![image](https://github.com/user-attachments/assets/26902d8b-4ede-419f-93ea-a194139391f4)
**The Contributing.md hyperlink is not redirecting to the correct file.**

![image](https://github.com/user-attachments/assets/b6d06aeb-240f-4ba5-8ebe-d9d0997fe529)
I would love to help you out with the following documentation bug and also look into your project documentation further for any improvements that would be possible from my end.

**Comment by vishanurag** [comment]
Closed by #159
