### ISSUE TITLE
I want to Drawing, Text, undo/ redo Functionalites , Background customization, 

### ISSUE THREAD

**Issue by JahnavikaGopalbvrith** [vishanurag/Canvas-Editor#137]
By incorporating these features and improvements, your canvas tool will become much more versatile and user-friendly.

**Comment by JahnavikaGopalbvrith** [comment]
Thank you for assigning me.I will let you know the update soon.

**Comment by JahnavikaGopalbvrith** [comment]
https://github.com/user-attachments/assets/7b18bd97-b89d-416c-99db-08f41e2fb2cb


Added welcome page to the website and font size ,font style, text color, pen style ,add text ,undo and redo functionalities 
@vishanurag once please review it. is that fine?
Any corrections? let me know.

**Comment by vishanurag** [comment]
Great work 👍

**Comment by JahnavikaGopalbvrith** [comment]
Thank you.

**Comment by vishanurag** [comment]
Closed via #190
