### ISSUE TITLE
Contact Section Needs Improvement

### ISSUE THREAD

**Issue by simmi-verma** [vishanurag/Canvas-Editor#155]
![Screenshot (1063)](https://github.com/user-attachments/assets/005d887c-b718-4e9e-bfd6-454dde47d806)
The contact section lacks clarity and organization. It should be structured with clear headings and easily accessible contact details to enhance user experience.
please assign to me

**Comment by Prithwi32** [comment]
@vishanurag please assign this task to me under gssoc and hacktoberfest

**Comment by shrutilad20** [comment]
As above in the issue the contact section isn't clarifying. The title is in white color and also the background and many other changes needed to be done.
Please aasign the task to me under gssoc and hacktoberfest.

**Comment by simmi-verma** [comment]
I have raised an issue and requested it to be assigned to me. Kindly assign it. Can you add gssoc-ext and level?

**Comment by simmi-verma** [comment]
Sir, you assigned me this issue, but I see that you have already merged it. I have spent a lot of time on this. What should I do now?

**Comment by simmi-verma** [comment]
sir I request you to you should merged which you have assigned otherwise

**Comment by simmi-verma** [comment]
sir I have solved this issue.

**Comment by simmi-verma** [comment]
Sir please reply me.
