### ISSUE TITLE
Hiding the distance between the mouse pointer and the actual brush on the canvas

### ISSUE THREAD

**Issue by sarinsanyal** [vishanurag/Canvas-Editor#156]
![Screenshot 2024-10-05 162407](https://github.com/user-attachments/assets/b31e18ac-1f04-45c5-a7c0-7e4a1d87dc6b)

https://github.com/user-attachments/assets/a287e85a-591a-4030-bf99-6e0fb7a7c62a

The brush doesn't create the color at the same position where the cursor is. Because of this distance, it looks weird.

At the left-most point, it works fine, but as we go right, the distance keeps on increasing. It probably is due to the coordinates being off, or a problem with the mouse event handling.

@vishanurag , please assign this to me. Also, please label it as Hacktoberfest and GSSoc Extended.

**Comment by vishanurag** [comment]
Closed via #187
