### ISSUE TITLE
CHANGING THE FOOTER

### ISSUE THREAD

**Issue by monishkumardvs** [vishanurag/Canvas-Editor#158]
![image](https://github.com/user-attachments/assets/1a984515-8be0-4490-a95e-f0e41f7dd5ab)
I WILL CHANGE THE FOOTER IN ORGANISED WAY. CAN U ASSIGN ME

**Comment by AhanaGanguly965** [comment]
I also want to add some features.Can u assign me this

**Comment by vishanurag** [comment]
Closed via #173
