### ISSUE TITLE
Adding subscript and superscripts in text for writing formulas

### ISSUE THREAD

**Issue by aditiverma-21** [vishanurag/Canvas-Editor#16]
Adding subscripts and superscripts is essential for writing mathematical formulas, chemical equations, and scientific notations.

**Comment by vishanurag** [comment]
Can you please give some clear information about your proposed idea?

**Comment by Pujitha254** [comment]
sir could you please assign this to me so that i can contribute in adding features like subscripts and superscripts for writing formulas

**Comment by vishanurag** [comment]
The similar issue is already assigned.
Refer issue #22 

You may create another issue

**Comment by BhavikaPachauri** [comment]
I would like to solve this issue

**Comment by aditiverma-21** [comment]
@vishanurag I wanted to add subscript and superscript like for chemical formal H2O (2 is subscript) and 2^2 that square power is superscript

**Comment by adarshsingh0103** [comment]
@aditiverma-21  Can you please! assign me to work on this issue.
