### ISSUE TITLE
Adding functionalities (eg. : undo/redo) to enhance user experience

### ISSUE THREAD

**Issue by tanishkagarg1911** [vishanurag/Canvas-Editor#17]
I want to add a shape/ icon pallete along  with undo and redo functionalities...the functionalities will help
 increase user experience

Please assign it to me sir @vishanurag

**Comment by tanishkagarg1911** [comment]
please assign it under gsoc ext and hacktoberfest, I am new to open source and want to gain hands on experience

**Comment by vishanurag** [comment]
Assigning this issue to you.

**Comment by tanishkagarg1911** [comment]
Thankyou  @vishanurag , I have started working on the issue !

**Comment by vishanurag** [comment]
Issue close by #49
