### ISSUE TITLE
Website Enhancements: Improved Design and Functionality

### ISSUE THREAD

**Issue by AnujShrivastava01** [vishanurag/Canvas-Editor#18]
The changes that can be made to the website are:

1. Right Box Background: Can be Changed to a darker color (#1c1c1c), making it visually distinct from the rest of the page.
2. Button Hover Effect : Buttons now change background color and slightly lift on hover, improving interactivity.
3. Canvas: Lightened the canvas background (#eaeaea) with a soft border, making it more appealing.
4. Overall Aesthetic: Applied modern font (Poppins) and softened corners (border-radius) for a smoother, clean design.
5. Form: The text input and buttons within the form have a more polished look with rounded corners and consistent spacing.

Assign me this issue , I am ready to work on this .

**Comment by vishanurag** [comment]
Ok. Assigning this issue to you.

**Comment by AnujShrivastava01** [comment]
Thankyou for assigning .

**Comment by rutikakengal** [comment]
I like to work on this issue . Assign me @vishanurag

**Comment by vishanurag** [comment]
Closed by pr #39
