### ISSUE TITLE
adding back to top button

### ISSUE THREAD

**Issue by saadgibawa** [vishanurag/Canvas-Editor#182]
Hi! @vishanurag 
Adding a "Back to Top" button would improve the page navigation by providing users a convenient way to return to the top without excessive scrolling.
I want to work on this so please assign me this issue

**Comment by samyak-aditya** [comment]
Hey @vishanurag Please Assign me this Task

**Comment by saadgibawa** [comment]
hey @vishanurag 
I was just working on this button feature but everything on the homepage is just so messed. Please assign the redesigning of homepage to me if is not assigned to someone else

**Comment by saadgibawa** [comment]
@vishanurag By the way, I have added a back to top button. Please let me know if the redesign of the homepage is assigned to someone else, so that I can raise the PR for just the button.
