### ISSUE TITLE
adding Routes to the page like About , Home , Designs with full Details

### ISSUE THREAD

**Issue by devxMani** [vishanurag/Canvas-Editor#19]
please assign this task to me and add Gssoc ext and Hacktoberfest label to this issue

**Comment by vishanurag** [comment]
Can you please provide a proper explanation on your proposed idea 💡?

**Comment by Pujitha254** [comment]
hey @vishanurag could you please assign this task to me ....so that i can help you in adding routes to the page like about ,Home ,Designs with full details

**Comment by vishanurag** [comment]
If you want to add routes/links with navbar, then I want to tell you, that the similar issue is already assigned earlier.
Refer issue #7

**Comment by Pujitha254** [comment]
sir please give me one chance to prove my self and add more interactive elements like this please check this out this sir
![Screenshot 2024-10-02 111734](https://github.com/user-attachments/assets/6bacabf3-5dc2-47c7-b4c8-fe200dd0ad38)

**Comment by vishanurag** [comment]
> sir please give me one chance to prove my self and add more interactive elements like this please check this out this sir ![Screenshot 2024-10-02 111734](https://private-user-images.githubusercontent.com/132841750/372743702-6bacabf3-5dc2-47c7-b4c8-fe200dd0ad38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NDg1NDQsIm5iZiI6MTcyNzg0ODI0NCwicGF0aCI6Ii8xMzI4NDE3NTAvMzcyNzQzNzAyLTZiYWNhYmYzLTVkYzItNDdjNy1iNGM4LWZlMjAwZGQwYWQzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQwNTUwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTdiZjJmYzM0YzFhNWY3YTZjNDdjZmI2NDVkYmYxYmI5OTk2NWI3NGQ5ZDQ1OGIzOTQxNDU1NzA2NTVmNzJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KBTseDXBYAjzmORHHxnD7-CoKQN-MA4jj8dJ85_v05I)

I know you want to work and excited. But the same issue is already assigned. Please try to understand.
You can create another issue maybe any other feature or bug fix.

**Comment by Pujitha254** [comment]
ok sir thankyou for your reply
