### ISSUE TITLE
Add GitHub Action that automatically displays all contributors in the README

### ISSUE THREAD

**Issue by shubhagarwal1** [vishanurag/Canvas-Editor#192]
Hey @vishanurag Please assign me this Task with label "gssoc-ext", "hacktoberfest-accepted" and "level2"

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.
and add the gssoc-ext label

**Comment by shubhagarwal1** [comment]
> Can you please assign it to me? I want to work on it. and add the gssoc-ext label

pr already raised
