### ISSUE TITLE
About us page looks very wage and image is broken

### ISSUE THREAD

**Issue by ngsanthosh** [vishanurag/Canvas-Editor#197]
Need to revamp about us page, as it is of non English language and the provided image is broken. 

![image](https://github.com/user-attachments/assets/bbf31d8f-fc71-4b14-bba1-4915448d6fbe)

**Comment by vikassahu1** [comment]
Hello, I want to work on this issue please assign me this work under label hacktoberfest.
Thank You!

**Comment by ngsanthosh** [comment]
I have worked on it brother, Can you please check some other issues, or enhancements that needs to be done. Sorry @vikassahu1

**Comment by vikassahu1** [comment]
ok @ngsanthosh

**Comment by vishanurag** [comment]
Closed via #184
