### ISSUE TITLE
Enhance Buttons, Icons, and Styles in Canvas Editor

### ISSUE THREAD

**Issue by Web-Dev-Learner** [vishanurag/Canvas-Editor#2]
As a newbie eager to contribute, I would like to propose improvements to the buttons, icons, and overall styles of the Canvas Editor project. The aim is to create a more visually appealing and user-friendly interface.

![Screenshot 2024-10-01 182631](https://github.com/user-attachments/assets/2051c1e5-9ec1-4511-b2a1-84c094dbdbe0)

Please assign this issue to me as I would like to work on these improvements. My GitHub username is Web-Dev-Learner.

Please add the label for GSSoC 2024 Extd. and relevant labels

**Comment by vishanurag** [comment]
@Web-Dev-Learner can you please provide some sample images of buttons, icons, etc which you are talking about.

**Comment by Web-Dev-Learner** [comment]
Thank you for your feedback regarding my proposal for improving the buttons and overall styles of the Canvas Editor project. I wanted to specifically highlight the arrangement of buttons and their padding, especially in the mobile view.


![Screenshot 2024-10-01 193143](https://github.com/user-attachments/assets/fe39494a-de2a-4bb7-b78a-983d07a369d5)

**Comment by vishanurag** [comment]
Ok I am assigning this issue to you.

**Comment by Web-Dev-Learner** [comment]
Thank you for assigning me as a contributor to the Project. I'm excited to start contributing and help improve the project.

Could you please add the "Hacktoberfest-accepted" label .This will ensure my contributions are counted towards Hacktoberfest.  Best regards,
Shrinedhi.M.R

**Comment by vishanurag** [comment]
Issue resolved by #14
