### ISSUE TITLE
Adding hyperlink to "ANURAG VISHWAKARMA "

### ISSUE THREAD

**Issue by nksmanya** [vishanurag/Canvas-Editor#204]
I would like to add hyperlink "ANURAG VISHWAKARMA " to their GitHub profile, in the footer section.
Please assign this task to me with the corresponding labels and levels @vishanurag

**Comment by VivekShahare04** [comment]
fix: Update footer links to ensure proper redirection

Related Issue
Closes: https://github.com/vishanurag/Canvas-Editor/issues/204

Description
In this pull request, I have resolved the issue with the footer links not directing users to the intended URLs. A hyperlink has been added to the footer for the name "ANURAG VISHWAKARMA," linking to the specified GitHub profile. This change enhances user accessibility to important social media and professional pages.

How Has This Been Tested? ⚙️
I tested the links in the footer by clicking on them and verifying that they redirect correctly to the specified URLs without any errors. The link to the GitHub profile opens in a new tab as expected.

Screenshots 📷
Screenshot 2024-10-06 154645

Type of change
What sort of changes have you made:

Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)
Code style update (formatting, local variables)
Breaking change (fix or feature that would cause existing functionality to not work as expected)
This change requires a documentation update

Checklist
My code follows the code style of this project.
I have followed the contribution guidelines.
I have performed a self-review of my own code.
I have ensured my changes don't generate any new warnings or errors.
I have updated the documentation (if necessary).
I have resolved all merge conflicts.

@vishanurag
