### ISSUE TITLE
improving user interface

### ISSUE THREAD

**Issue by kartik9737** [vishanurag/Canvas-Editor#218]
can you assign me a work to improve user interface as some text is not visible in original one
@vishanurag 
![Screenshot 2024-10-06 133038](https://github.com/user-attachments/assets/71ed1e2e-2157-4bd3-8cdf-aff58d8b9869)
![Screenshot 2024-10-06 133109](https://github.com/user-attachments/assets/cfa9caf1-6157-43d0-afd2-4bb1b79fd913)

**Comment by Akanshaku** [comment]
I would like to work on this issue pls assign me this @vishanurag

**Comment by aryansoni13** [comment]
would like to work on this kindly assign me the task

**Comment by vishanurag** [comment]
closed via #294
