### ISSUE TITLE
Dark Font Palette Issue

### ISSUE THREAD

**Issue by snehhhcodes** [vishanurag/Canvas-Editor#222]
Hello @vishanurag !!

I hope this message finds you well. I would like to address an issue I encountered on the website and propose a solution that I believe will enhance the user experience:

# Issue Description:
The palette's font colour is too dark, which can cause readability issues for users. Dark fonts on certain backgrounds or low-contrast environments may lead to eye strain, making it difficult for users to engage with the content. This can negatively impact user experience, especially for those with visual impairments or when viewed in different lighting conditions.

# Proposed Solution:
To resolve the issue of the font being too dark, I will adjust the palette by lightening the font colour to create better contrast with the background. This will make the text easier to read, improving the overall user experience. 

# Image/Video:
Adding a visual so that you can easily review and verify the issue.
![Screenshot 2024-10-06 133522](https://github.com/user-attachments/assets/dbf0ad2e-cb62-4ab7-beca-ba5438fece6c)

If you find this proposal suitable, I would appreciate it if you could assign these tasks to me.

**Comment by snehhhcodes** [comment]
@vishanurag thnku for assigning it to me anurag but i have some query by any chance are u checking the pr before merging it as i clone the repo just now and checked the pallete to draw is whole gone and pallete for choosing brush and color are now twice at home page.

[screen-capture.webm](https://github.com/user-attachments/assets/703b40f3-b392-4c96-bf4a-77a77158d1a5)

**Comment by snehhhcodes** [comment]
@vishanurag hope you will reply as my assigned issue was to chng the dark font for the pallete and now they are clearly two palletes for choosing brush n all

**Comment by vishanurag** [comment]
> @vishanurag thnku for assigning it to me anurag but i have some query by any chance are u checking the pr before merging it as i clone the repo just now and checked the pallete to draw is whole gone and pallete for choosing brush and color are now twice at home page.
> 
>  screen-capture.webm

@snehhhcodes 
I am extremely sorry for the inconvenience. Someone might have created this problem while resolving the merge conflicts.
Sometimes it's really hard to check every single mistake or bug created by contributors because there are so many people contributing and it's really hard to go through every problem as a PA because there is no other maintainer of this project other than me. Hope you understand.

You can still contribute to this project.
Sorry for the inconvenience happen with you. 🙏

**Comment by snehhhcodes** [comment]
> > @vishanurag thnku for assigning it to me anurag but i have some query by any chance are u checking the pr before merging it as i clone the repo just now and checked the pallete to draw is whole gone and pallete for choosing brush and color are now twice at home page.
> > screen-capture.webm
> 
> @snehhhcodes I am extremely sorry for the inconvenience. Someone might have created this problem while resolving the merge conflicts. Sometimes it's really hard to check every single mistake or bug created by contributors because there are so many people contributing and it's really hard to go through every problem as a PA because there is no other maintainer of this project other than me. Hope you understand.
> 
> You can still contribute to this project. Sorry for the inconvenience happen with you. 🙏

should i feix it too if you can change the label to level2 i can do it!!

**Comment by vishanurag** [comment]
Closed via #244
