### ISSUE TITLE
Text is not visible

### ISSUE THREAD

**Issue by ash-k121** [vishanurag/Canvas-Editor#23]
After writing the text and adding the background color the text disappears 
![image](https://github.com/user-attachments/assets/a54b817d-2d8b-48be-b637-84a529f65723)

**Comment by vishanurag** [comment]
Hmm 🤔 I see.

If you want to work on this issue then simply type yes. I'll assign it to you.

**Comment by PThanushree** [comment]
Yes

**Comment by ash-k121** [comment]
> Hmm 🤔 I see.
> 
> If you want to work on this issue then simply type yes. I'll assign it to you.

yes please assign this to me
