### ISSUE TITLE
Add support for multiple text elements on canvas

### ISSUE THREAD

**Issue by Sagar2006** [vishanurag/Canvas-Editor#26]
## Description
Currently, the canvas only supports a single text element. To enhance the functionality and versatility of our text editor, we should implement support for multiple text elements on the canvas.

## Proposed Changes
1. Modify the data structure to store multiple text elements
2. Update the rendering logic to display all text elements
3. Add a new "Add Text" button to create additional text elements
4. Modify the existing "Save" button to update the currently selected text element
5. Implement a selection mechanism for choosing which text element to edit

## Implementation Details
- Create a new array `textElements` to store multiple text objects
- Update `addToSnapSorts()` to handle multiple elements
- Create new functions `addTextElement()` and `renderAllElements()`
- Modify `updateCanvas()` to work with multiple elements
- Add a new event listener for the "Add Text" button
- Update the HTML to include the new "Add Text" button

kindly assign this issue to me

**Comment by vishanurag** [comment]
Sure! Assigning this issue to you.

**Comment by Sagar2006** [comment]
Kindly check the Pull request for this issue.
Please comment with any suggestions or concerns about this proposed feature.
