### ISSUE TITLE
Submit Button Functionality

### ISSUE THREAD

**Issue by prishsha** [vishanurag/Canvas-Editor#287]
Currently when the user fills the fields and clicks on the Submit Button, the page simply refreshes. I would like to add a functionality where upon clicking the submit button, an alert is displayed saying "Your response is recorded". This would enhance user interaction. 
![image](https://github.com/user-attachments/assets/2715db80-a3c5-4e92-af7f-b68eacbd9a2e)
Kindly assign me this issue under the labels gssoc-ext, hacktoberfest-accepted and level of the problem

**Comment by icemberg** [comment]
can you please assign this issue to me
