### ISSUE TITLE
Add Pre-loader

### ISSUE THREAD

**Issue by soumyajit254** [vishanurag/Canvas-Editor#299]
Sir,
 I want to contribute in this project. I can add Pre- loader. Please assign me this

**Comment by Achbi** [comment]
I want to contribute in this project

**Comment by VidhanThakur09** [comment]
@vishanurag I have already fixed this issue, kindly see the PR's
![Screenshot 2024-10-09 124552](https://github.com/user-attachments/assets/add0cb2c-c30a-4e56-82e4-83d690cb1724)


Issue number #230 
Pr number #276
