### ISSUE TITLE
Enhancing web page 

### ISSUE THREAD

**Issue by Pranshu-jais** [vishanurag/Canvas-Editor#3]
I want to make the  webpage more user friendly , by adding  css  styles and including  web page responsiveness . please assign this issue to me  as gssoc-ext contributor  with appropriate level .

**Comment by vishanurag** [comment]
@Pranshu-jais go ahead.

**Comment by Ananya-vastare** [comment]
I am GSSOC contributor may I enhance the webpage

**Comment by vishanurag** [comment]
> I am GSSOC contributor may I enhance the webpage

@Ananya-vastare this issue had already assigned. you can simply create a new issue.

**Comment by souvikpramanikgit** [comment]
Can you assign me this issue, i will enhance the webpage
