### ISSUE TITLE
navbar underline hover effect

### ISSUE THREAD

**Issue by Krishnamverma951** [vishanurag/Canvas-Editor#301]
![image](https://github.com/user-attachments/assets/810440f7-aa40-4d60-b404-ff6f70e9a52a)

https://github.com/user-attachments/assets/d335f9a4-5a13-450e-acc0-4ae674b14810

please assign me

**Comment by Akanshaku** [comment]
I would like to work on this issue pls assign me this @vishanurag

**Comment by Krishnamverma951** [comment]
@vishanurag  301 issue no
