### ISSUE TITLE
No Hover Animation on Social Icons

### ISSUE THREAD

**Issue by PATILYASHH** [vishanurag/Canvas-Editor#305]
#### Description
The social icons currently lack any hover animation, which makes them appear static and less engaging. By adding hover effects, we can improve the visual appeal and interactivity of the icons, making them look more dynamic and visually pleasing when the user interacts with them.

#### Steps to Reproduce
1. View the social icons on the page.
2. Hover over the icons.
3. Notice that no hover animation is applied.

#### Expected Behavior
- Social icons should have smooth and visually appealing hover animations when the user hovers over them.
- This will make the icons more engaging and provide a better user experience.

#### Possible Solution
- Add CSS hover animations to the social icons to enhance their appearance. This could include scaling, color transitions, or other subtle effects that improve the overall look and feel.

#### Screenshot
![image](https://github.com/user-attachments/assets/d566b9e4-89a7-46f8-ac8d-f9bf7195749a)

#### Additional Context
By adding hover effects, the icons will look more polished and interactive, enhancing the design and making them stand out.

**Comment by bhavana-katari** [comment]
I would like to work on this project. Please assign it to me

**Comment by Keerthanasrs** [comment]
i am excited to do this !please assign it to me.
