### ISSUE TITLE
Styling the Vertical Scrollbar

### ISSUE THREAD

**Issue by Tanushree084** [vishanurag/Canvas-Editor#311]
Hey @vishanurag 

I want to style the vertical scrollbar of the website, currently it is default.

I want to make it like below. (Will follow the website theme like blue-purple combination)
<img width="74" alt="image" src="https://github.com/user-attachments/assets/a843f5fe-4b14-40a5-9896-c0a3a7317365">

Please assign me this task under gssoc-ext and hactoberfest.

**Comment by VidhanThakur09** [comment]
@vishanurag I have already fixed this issue, kindly see the PR's
![Screenshot 2024-10-09 124552](https://github.com/user-attachments/assets/add0cb2c-c30a-4e56-82e4-83d690cb1724)


Issue number #230 
Pr number #276
