### ISSUE TITLE
Updation of Footer Icons on all pages and addition of Reponsiveness on the Icons.

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [vishanurag/Canvas-Editor#318]
![image](https://github.com/user-attachments/assets/03ab9536-f405-4119-b21c-30c83406aa1f)

The Footer icons are not responsive(do not redirect to the respective sites)

I would like to work on the issue.

**Comment by Akanshaku** [comment]
I would like to work on this issue pls assign me this @vishanurag

**Comment by rajdeepchakraborty-rc** [comment]
@vishanurag thanks for assigning me the issue. Could you provide me with any pages if you have on these websites? If you do not have any let me know

**Comment by rajdeepchakraborty-rc** [comment]
> I would like to work on this issue pls assign me this @vishanurag

It is already assigned to me. Please try any work on any other issue

**Comment by vishanurag** [comment]
LinkedIn: https://www.linkedin.com/in/anuragvishwakarma/

This is the only one social media I have...😅

**Comment by rajdeepchakraborty-rc** [comment]
> LinkedIn: https://www.linkedin.com/in/anuragvishwakarma/
> 
> This is the only one social media I have...😅

Ok thanks a lot for providing me. Leave the rest to me. I will update you regarding the work and if I need something.

**Comment by rajdeepchakraborty-rc** [comment]
@vishanurag I noticed that you have different icons on different pages which is looking very poor. Do you want me to update the icons of the other pages to match as that of on the Home page? Since I will be working on the icons.
I will keep the following icons on all the pages:
![image](https://github.com/user-attachments/assets/4b593284-2a26-4938-9dcb-3557d634ec97)
Please let me know if you want me to work on it.

**Comment by rajdeepchakraborty-rc** [comment]
> @vishanurag I noticed that you have different icons on different pages which is looking very poor. Having uniform icons throughout the website pages will increase the website's usability and readability! Do you want me to update the icons of the other pages to match as that of on the Home page? Since I will be working on the icons. I will keep the following icons on all the pages: ![image](https://private-user-images.githubusercontent.com/68934988/375060239-4b593284-2a26-4938-9dcb-3557d634ec97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0OTc5NzQsIm5iZiI6MTcyODQ5NzY3NCwicGF0aCI6Ii82ODkzNDk4OC8zNzUwNjAyMzktNGI1OTMyODQtMmEyNi00OTM4LTlkY2ItMzU1N2Q2MzRlYzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDE4MTQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5M2Y1YmI2NDM0YTVjM2QyMjIxOGFiMTVjMzc0NzEyYzM1ZWNlNjcyN2Q3NzJlNjAxYjlhYzFhMGQ3M2YxNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._KZRUcStEFtzEaxIWibz3tLV9xiCoXzG_MEvu1CFAVE) Please let me know if you want me to work on it.

@vishanurag Please update me regarding this so that I can start working on the issue.

**Comment by rajdeepchakraborty-rc** [comment]
@vishanurag Please let me know

**Comment by rajdeepchakraborty-rc** [comment]
@vishanurag please check and let me know

**Comment by rajdeepchakraborty-rc** [comment]
@vishanurag please check your messages and update me.

**Comment by vishanurag** [comment]
> > @vishanurag I noticed that you have different icons on different pages which is looking very poor. Having uniform icons throughout the website pages will increase the website's usability and readability! Do you want me to update the icons of the other pages to match as that of on the Home page? Since I will be working on the icons. I will keep the following icons on all the pages: ![image](https://private-user-images.githubusercontent.com/68934988/375060239-4b593284-2a26-4938-9dcb-3557d634ec97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0OTc5NzQsIm5iZiI6MTcyODQ5NzY3NCwicGF0aCI6Ii82ODkzNDk4OC8zNzUwNjAyMzktNGI1OTMyODQtMmEyNi00OTM4LTlkY2ItMzU1N2Q2MzRlYzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDE4MTQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5M2Y1YmI2NDM0YTVjM2QyMjIxOGFiMTVjMzc0NzEyYzM1ZWNlNjcyN2Q3NzJlNjAxYjlhYzFhMGQ3M2YxNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._KZRUcStEFtzEaxIWibz3tLV9xiCoXzG_MEvu1CFAVE) Please let me know if you want me to work on it.
> 
> @vishanurag Please update me regarding this so that I can start working on the issue.

@rajdeepchakraborty-rc yes you can work on this

**Comment by rajdeepchakraborty-rc** [comment]
> > > @vishanurag I noticed that you have different icons on different pages which is looking very poor. Having uniform icons throughout the website pages will increase the website's usability and readability! Do you want me to update the icons of the other pages to match as that of on the Home page? Since I will be working on the icons. I will keep the following icons on all the pages: ![image](https://private-user-images.githubusercontent.com/68934988/375060239-4b593284-2a26-4938-9dcb-3557d634ec97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0OTc5NzQsIm5iZiI6MTcyODQ5NzY3NCwicGF0aCI6Ii82ODkzNDk4OC8zNzUwNjAyMzktNGI1OTMyODQtMmEyNi00OTM4LTlkY2ItMzU1N2Q2MzRlYzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDE4MTQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5M2Y1YmI2NDM0YTVjM2QyMjIxOGFiMTVjMzc0NzEyYzM1ZWNlNjcyN2Q3NzJlNjAxYjlhYzFhMGQ3M2YxNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._KZRUcStEFtzEaxIWibz3tLV9xiCoXzG_MEvu1CFAVE) Please let me know if you want me to work on it.
> > 
> > 
> > @vishanurag Please update me regarding this so that I can start working on the issue.
> 
> @rajdeepchakraborty-rc yes you can work on this

@vishanurag Ok. I will work on the following too. Please do update the issue to **level2**.

**Comment by rajdeepchakraborty-rc** [comment]
There were some code errors in some of the CSS files that were causing an issue to me. I have updated those files.

**Comment by rajdeepchakraborty-rc** [comment]
Also some pages were using the old icon of Twitter:
![image](https://github.com/user-attachments/assets/3f43fbd3-532b-478c-b194-77738fa7f754)
I have updated them to the new logo of Twitter(X).
![image](https://github.com/user-attachments/assets/61d3df5f-e483-4abf-8249-7a8809e89374)
I have added the above logos on all the pages.

**Comment by rajdeepchakraborty-rc** [comment]
There were also mismatch of the types of logo used: 
(Notice the LinkedIn logo)

- Review Page

![image](https://github.com/user-attachments/assets/a7bd6fc4-ebfb-4cf5-bf83-5046982af798)

- About Us page
![image](https://github.com/user-attachments/assets/91be5578-b24b-4340-bf0f-01e271d8270a)

I have resolved that issue too.

**Comment by rajdeepchakraborty-rc** [comment]
@vishanurag I am done with the main work. I will just add some finishing touches and open a PR soon. By the time, you can see this messages and let me know how they are or if they require any change.
