### ISSUE TITLE
Auto commenting on New Issue Creation

### ISSUE THREAD

**Issue by sejals23** [vishanurag/Canvas-Editor#343]
It automatically adds comments to the description of a newly created issue, providing helpful information, context, or reminders. This ensures that all issues include essential details or instructions, improving the quality of reports. It ensures that comments on issues follow a consistent format or structure. This helps teams maintain a standardized approach to handling issues, reducing confusion and misunderstandings.  Users don’t need to manually add repetitive information or instructions. The automatic comment can include standard guidelines, troubleshooting steps, or links to documentation.

**Comment by vishanurag** [comment]
similar feature is already added.
