### ISSUE TITLE
Alignment and Spacing

### ISSUE THREAD

**Issue by Poushmita** [vishanurag/Canvas-Editor#35]
# Description

 Can improve the alignment between the canvas area and the control panel, the buttons.

# Screenshot

<img width="732" alt="i1" src="https://github.com/user-attachments/assets/21be3bfe-43ba-4aaa-bd97-3d0f440287b4">

# Additional Information

It's ensure consistent spacing to make the layout more appealing. It also enhance the readability of the webpage and the user-experience.

**Comment by Khushi-Nigam** [comment]
I can Resolve this issue please assignn this project to me.

**Comment by Poushmita** [comment]
@Khushi-Nigam  Hi, Khushi !!
You can group with me, if you want to solve this issue.

**Comment by vishanurag** [comment]
Ok. Assigning this issue to both of you.

**Comment by Khushi-Nigam** [comment]
@Poushmita You Can Connect with me on linkedin
[https://www.linkedin.com/in/khushi-nigam-b54088271/](url)

**Comment by Khushi-Nigam** [comment]
> @Khushi-Nigam if you want to work on this issue, then contact with me or tell me how to contact with you.
> 
> `Please response , otherwise I will take it as you r not willing to work on this. `

You can go ahead with this

**Comment by Poushmita** [comment]
@Khushi-Nigam   Okay
