### ISSUE TITLE
Button Styles

### ISSUE THREAD

**Issue by Poushmita** [vishanurag/Canvas-Editor#36]
# Description

Can enhance the buttons (e.g., "A," "B," "Save," etc.) by applying better styling.

# Screenshot

<img width="732" alt="i1" src="https://github.com/user-attachments/assets/21be3bfe-43ba-4aaa-bd97-3d0f440287b4">

# Additional Information

Can use hover effects, shadows, or even animations for a more interactive feel with the webpage to enhance the user-experience.

**Comment by simmi-verma** [comment]
I would like to contribute in it .Please add label of gssoc-ext 24 and assign  to me.

**Comment by vishanurag** [comment]
You both can discuss with each other. And then tell me, should I assign this issue to both of you or on of you.

**Comment by Abhi0049k** [comment]
@vishanurag can you assign this issue to me?

**Comment by Poushmita** [comment]
@vishanurag  I would like to do this by myself only but if you want then can assign only one person with me.

**Comment by sanjanasp786** [comment]
i would like to do this ...please assign it to me

**Comment by Poushmita** [comment]
@vishanurag  kindly, assign me .

**Comment by RishabxBhardwaj** [comment]
i'll give it try
