### ISSUE TITLE
Drag-and-Drop Feature

### ISSUE THREAD

**Issue by Poushmita** [vishanurag/Canvas-Editor#37]
# Description

Can refine the drag-and-drop functionality of text on the canvas.

# Additional Information

Ensures smooth transitions when users move and position text objects, improving the overall user experience.

**Comment by simmi-verma** [comment]
I would like to contribute in it .Please add label of gssoc-ext 24 and assign to me.

**Comment by vishanurag** [comment]
You both can discuss with each other. And then tell me, should I assign this issue to both of you or one of you.

**Comment by Poushmita** [comment]
@vishanurag  I can group .

**Comment by sanjanasp786** [comment]
i would like to contribute in it....please assign it to me

**Comment by simmi-verma** [comment]
I would appreciate it if you assign it to me, but if you prefer, you can assign it to both of them.

**Comment by simmi-verma** [comment]
Please add gssoc-ext label.

**Comment by Poushmita** [comment]
@simmi-verma  please contact with me or tell me how to contact with you?

**Comment by simmi-verma** [comment]
You can reach me through LinkedIn

**Comment by Poushmita** [comment]
okay
