### ISSUE TITLE
Issue: Enhance the Footer Section UI

### ISSUE THREAD

**Issue by sahhoArjun097** [vishanurag/Canvas-Editor#376]
The current footer section of the website can be improved to provide a better user experience and visual appeal. The existing design lacks modern UI elements and could benefit from updates that make it more visually engaging, functional, and aligned with the overall website design.

-Modern Layout: Restructure the footer to incorporate a cleaner, grid-based design that aligns with the rest of the site’s modern look and feel.

-Social Media Icons: Add interactive, well-designed icons for social media links, making them more prominent and visually appealing rather than the previous icons.

-Use background colors or gradients that complement the site’s color palette, enhancing overall aesthetics.

![Screenshot 2024-10-10 201648](https://github.com/user-attachments/assets/09c3f7c7-81f4-4d3d-92b6-f7d4cf645edc)

**Comment by Pragya79645** [comment]
I would like to work on it
