### ISSUE TITLE
Improvement in Designing of This project

### ISSUE THREAD

**Issue by Khushi-Nigam** [vishanurag/Canvas-Editor#38]
I want to do desgning of this project so that it will look more attractive and user friendly. Please assign me this project , I have to work on it. Also Please add the desired labels

**Comment by Ishika-codeit** [comment]
i also want to design this project more awesome by my great knowledga kindly issue it to me...
thank you!!

**Comment by vishanurag** [comment]
You both can discuss with each other. And then tell me, should I assign this issue to both of you or one of you.

**Comment by Khushi-Nigam** [comment]
@Ishika-codeit Sure i'll be happy to contribute together..

**Comment by Khushi-Nigam** [comment]
@vishanurag Please add level also

**Comment by vishanurag** [comment]
> @vishanurag Please add level also

I have already add labels

![Screenshot_2024-10-02-23-15-11-013_com android chrome-edit](https://github.com/user-attachments/assets/c40b5dcf-72da-441f-bf3f-efb424013668)
