### ISSUE TITLE
🐞[Bug]: Unnecessary Black Element on Top-Left Corner of Website

### ISSUE THREAD

**Issue by priyachau12** [vishanurag/Canvas-Editor#391]
Describe the Bug
An unintended black element is displayed in the top-left corner of the website, which disrupts the visual appearance and could distract users.

Observed Behavior:
A black dot or shape appears on the top-left corner of the page without any functional purpose.

Expected Behavior
The website should have a clean and clutter-free layout, with no extra elements visible in the top-left corner unless intentionally placed for design.

![image](https://github.com/user-attachments/assets/9fb01ad1-f179-45e7-bce0-500c7fcceedf)

**Comment by vishanurag** [comment]
Issue already resolved
