### ISSUE TITLE
Add toggle button for password field in signup and login page

### ISSUE THREAD

**Issue by swathivemula7** [vishanurag/Canvas-Editor#393]
I would like to add a toggle button (eye icon) in the  password field in signup and login page
![Capturemcdmv](https://github.com/user-attachments/assets/1ea50155-0f3e-4284-bee6-135de4f173a6)

@vishanurag Kindly assign me this task under the labels gssoc;24 and hackatoberfest

**Comment by vishanurag** [comment]
Closed via #520
