### ISSUE TITLE
Features: The Join Community 

### ISSUE THREAD

**Issue by Lekkhasri** [vishanurag/Canvas-Editor#412]
The join community button is not working , which takes back to the about us .
I would like to work on this issue. When the user click the join community it takes you to the new page where the user can see the project managers, project admins and mentors details, their photo and social media links which make the page more enhancing.
Can you assign the issue to me @vishanurag 
i already have an experience in creating this pages.

![image](https://github.com/user-attachments/assets/7f111e48-510f-432b-82f4-ad8d68e01a83)

**Comment by vishanurag** [comment]
Important Profiles:

Project Admin: https://github.com/vishanurag
Project Mentor: https://github.com/somyadipghosh
