### ISSUE TITLE
"Draw here" text is not visible as you can see in the image  i am sharing ! 

### ISSUE THREAD

**Issue by 2004pra** [vishanurag/Canvas-Editor#441]
@vishanurag 
As you can see the color is not good for the text 'draw here' 
please assign me this task under gssoc extd24 , and hactober fest .
this is my first **issue** so i am trying with basic issues please assign me !
![Screenshot 2024-10-12 140055](https://github.com/user-attachments/assets/dae76bac-e340-47dd-9dc1-199dccd55b0b)

**Comment by harshvyas-22** [comment]
i would like to contribute to this repo please assign this to me

**Comment by 2004pra** [comment]
you assigned me the issue i raised for [ "draw here " text is not visible ] and now it has been changed by someone else and you are not accepting my pull request . please tell me if there is any problem

**Comment by 2004pra** [comment]
have i done something wrong !
please tell me 
@vishanurag 
![Screenshot 2024-10-12 215628](https://github.com/user-attachments/assets/24a4ee5b-e179-46e2-a746-fa19f642379a)

**Comment by vishanurag** [comment]
> have i done something wrong ! please tell me @vishanurag ![Screenshot 2024-10-12 215628](https://private-user-images.githubusercontent.com/102900421/375971424-24a4ee5b-e179-46e2-a746-fa19f642379a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NTU4NzksIm5iZiI6MTcyODc1NTU3OSwicGF0aCI6Ii8xMDI5MDA0MjEvMzc1OTcxNDI0LTI0YTRlZTViLWUxNzktNDZlMi1hNzQ2LWZhMTlmNjQyMzc5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQxNzUyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjA5OTYxMGYxY2M1Mzg2MDRjMTQ2NDk1NWE2MjRhNzIxYmNhMGU5ZmM4N2UwNDE1NTcwOWU2M2NlZDIwNDQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.T4qzyPBUsvwcfCyTKwAFOseHVxON03bqnxcjWdS8vik)


It looks like you merged your PR to your forked repository not in the vishanurag/Canvas-Editor/

Try to understand that you need to raise PR for the original repository not in the forked repo.

**Comment by 2004pra** [comment]
But the changes have been made by someone else what should I do now

**Comment by 2004pra** [comment]
I am closing my issue
