### ISSUE TITLE
Add Newsletter Subscription Section.

### ISSUE THREAD

**Issue by Palmistry2310** [vishanurag/Canvas-Editor#454]
We need to add a newsletter subscription section to the homepage to allow users to easily subscribe and stay updated with the latest blog posts, and updates.
Design user-friendly newsletter subscription section on the homepage. Add an input field for the user's email address and include a "Subscribe" button.

**Functionality:**
- The form should validate the email input for proper format (e.g., user@example.com).
- Display a confirmation message after the user successfully subscribes.

![Screenshot 2024-10-12 200911](https://github.com/user-attachments/assets/acd391d3-52f3-470a-8af4-9a20ea10720e)

@vishanurag can u assign me this issue under the gssoc-ext, hacktoberfest-accepted and level labels?

**Comment by Palmistry2310** [comment]
@vishanurag I will integrate a responsive message that is visible across different devices and Debouncing form submission(Implement debouncing to prevent rapid successive form submissions) if you consider upgrading the level. Please let me know!

**Comment by vishanurag** [comment]
> @vishanurag I will integrate a responsive message that is visible across different devices and Debouncing form submission(Implement debouncing to prevent rapid successive form submissions) if you consider upgrading the level. Please let me know!

Yea, sure 👍
