### ISSUE TITLE
Creating and adding consistent navbar 

### ISSUE THREAD

**Issue by Palmistry2310** [vishanurag/Canvas-Editor#455]
Creating a new nav bar from scratch such that it enhance and improve the current nav bar design.
will be creating navbar similar to below img (just an example rest theme would be according to the website) and sticking it to the top
![Screenshot 2024-10-12 194711](https://github.com/user-attachments/assets/10a99c3a-bc0a-4ef0-bf9c-1ad7f8eb4674)

@vishanurag i would really like to work on navbar, can you please assign this issue to me under gssoc-ext , hacktoberfest-accepted and level label?

**Comment by Palmistry2310** [comment]
@vishanurag I have one suggestion. As i observed the the navbar across all pages is inconsistent and missing at some pages(due to which there are several issues raised for adding back button on those pages) and in future too, multiple issues can be raised for that(like responsiveness, missing navbar etc etc) So if there are multiple people working on one navbar across different pages can create non-uniformity. 

As i m already designing the navbar for this issue, i can make it responsive and add it across all the pages due to which several present and future issues can be closed with just one pr. This can also make your work smooth and consistency of website remains intact.

Do let me know your review on this!

**Comment by vishanurag** [comment]
Great idea

**Comment by Palmistry2310** [comment]
> Great idea

should i edit the title and description of this issue?
And also i will make the navbar responsive. After the discussed changes, can you consider upgrading the level label to level-3?
