### ISSUE TITLE
Recreating the FAQ page 

### ISSUE THREAD

**Issue by Palmistry2310** [vishanurag/Canvas-Editor#457]
The current faq page looks inconsistent with the website theme. It also lacks the various things such as navbar and footer.
![Screenshot 2024-10-12 202511](https://github.com/user-attachments/assets/b433ea26-a69c-40b0-8ff7-285b80d990bf)

I can create a new **responsive faq page**  which integrates the navbar , footer and also matches the theme of the website.
@vishanurag can you please assign this issue to me under the gssoc-ext, hacktoberfest-accepted and level label?

**Comment by vishanurag** [comment]
Similar issue already assigned
