### ISSUE TITLE
Make the layout look prettier and fix the overflow to the right

### ISSUE THREAD

**Issue by hannah-maria** [vishanurag/Canvas-Editor#46]
- add styles to enhance the ui of the page 
- fix the overflow as ur able to scroll a little to the right

Consider assigning me this issue with tags gssoc and hactoberfest

**Comment by vishanurag** [comment]
Hmm I see.
Please fix that overflow issue.

**Comment by hannah-maria** [comment]
alright! just the overflow? @vishanurag

**Comment by vishanurag** [comment]
Yes

**Comment by hannah-maria** [comment]
@vishanurag since the pr has been merged ,kindly close the issue, thank you !
