### ISSUE TITLE
Hovering effect on nav bar

### ISSUE THREAD

**Issue by Son7c** [vishanurag/Canvas-Editor#472]
The hovering effect on the nav bar can be improved  and made better

https://github.com/user-attachments/assets/6c2aa6c4-6b5c-4adc-bb4e-3d7412415435

@vishanurag Kindly Assign this issue to me i would like to contribute in this.

**Comment by Son7c** [comment]
@vishanurag Kindly assign this issue to me

**Comment by vishanurag** [comment]
Similar issue is already assigned to someone else
