### ISSUE TITLE
Preloader Disappears Too Quickly – Increase Display Time

### ISSUE THREAD

**Issue by AsmitaMishra24** [vishanurag/Canvas-Editor#482]
The current duration of the preloader is too short, which causes issues with users noticing or understanding that loading is in progress. To improve user experience, I propose increasing the preloader time.

https://github.com/user-attachments/assets/565750e5-8c1b-4af1-b09e-1f95edc0cd39

**Comment by vishanurag** [comment]
I think that, increasing loading time will irritate users.
So this feature is not needed
