### ISSUE TITLE
i think their some more feature to edit the text

### ISSUE THREAD

**Issue by adityalaxkar123** [vishanurag/Canvas-Editor#5]

**Comment by adityalaxkar123** [comment]
like capitalise,small,italic and bold the letter

**Comment by adityalaxkar123** [comment]
me a gssoc'24 extended contributor can you assign it to me

**Comment by vishanurag** [comment]
Yes great idea 💡 
If you want to work on this issue then please type yes . I'll assign it to you...

**Comment by adityalaxkar123** [comment]
yes

**Comment by vishanurag** [comment]
Ok. Assigning to you
