### ISSUE TITLE
duplication of message box

### ISSUE THREAD

**Issue by Kajalmehta29** [vishanurag/Canvas-Editor#513]
Here message box is twice so i want to fix this issue.
Please assign this issue to me under gssoc-extd and hacktoberfest.

<img width="1103" alt="Screenshot 2024-10-13 at 6 40 09 PM" src="https://github.com/user-attachments/assets/4b904803-1202-4900-86d6-e89f274fd8a7">

**Comment by JOSHITHA6** [comment]
I have solved this issue @vishanurag . Please tag me under gssoc'24 extd and hacktoberfest.

![Screenshot (188)](https://github.com/user-attachments/assets/aa6e9253-238d-466b-b8f2-ccb428f1a419)

**Comment by vishanurag** [comment]
Closed via #1027
