### ISSUE TITLE
want to add animations using gsap

### ISSUE THREAD

**Issue by priyashuu** [vishanurag/Canvas-Editor#52]
Objective: I propose enhancing the homepage with text animations using GSAP (GreenSock Animation Platform) to improve user engagement and make the interface more dynamic.

Details:

Animate heading and subheading text on page load.
Include subtle fade-in or slide-in animations for improved visual appeal.
Ensure animations are responsive and do not affect performance on lower-end devices.
Will add comments to code to ensure clarity for future contributors.
Please assign this issue to me, as I would love to work on it. I am also a contributor in GGSOCExt 24 , hacktoberfest.

Looking forward to your feedback!

**Comment by sambedan1** [comment]
Objective:
I propose elevating the homepage experience by incorporating engaging text animations using GSAP (GreenSock Animation Platform), aiming to captivate users and create a more dynamic, interactive interface.

Details:
Animate the heading and subheading text with smooth, eye-catching effects triggered on page load.
Integrate subtle fade-in or slide-in animations to enhance the visual flow without overwhelming the design.
Optimize animations to be fully responsive and ensure they maintain seamless performance on lower-end devices.
Provide clear, well-documented code with detailed comments to facilitate ease of understanding for future contributors.

please assign this to me and add the tag ext-gssoc
