### ISSUE TITLE
update the footer section

### ISSUE THREAD

**Issue by rounakdey6** [vishanurag/Canvas-Editor#524]
please assign this issue

**Comment by JOSHITHA6** [comment]
@vishanurag I have solved this issue. Kindly merge this to me under labels gssoc'24 extd, hacktoberfest.
![footer](https://github.com/user-attachments/assets/b69d8924-8b41-4523-a682-c3fbf716f68e)

**Comment by vishanurag** [comment]
Closed via #1027
