### ISSUE TITLE
Alignment of buttons on Home page

### ISSUE THREAD

**Issue by BrindaManani** [vishanurag/Canvas-Editor#545]
The buttons on the home page are misaligned and also a "Home" buttons is displayed twice. This affect the overall visual appeal and usability of the interface. 

I would like to contribute to solve this issue. So, please assign it to me.

![CanvasEditor](https://github.com/user-attachments/assets/214b53d6-6e39-46df-8c6a-f6c7f0348c23)

**Comment by JOSHITHA6** [comment]
I have solved this issue @vishanurag . Please tag me under gssoc'24 and hacktoberfest.

![added_buttons_canvas_gssoc](https://github.com/user-attachments/assets/525afc2e-3da2-4d6b-adbd-84ba94c4b8e3)

**Comment by vishanurag** [comment]
Closed via #1027
