### ISSUE TITLE
Improve the css of the welcome banner

### ISSUE THREAD

**Issue by JOSHITHA6** [vishanurag/Canvas-Editor#555]
I have noticed that the css used for welcome is not looking compatible with the entire page. So kindly assign this issue to me under the label gssoc'24 extd and hacktoberfest @vishanurag 

![Screenshot (187)](https://github.com/user-attachments/assets/b7a01c6e-e8cc-4626-ac5b-27214cbf2496)

**Comment by JOSHITHA6** [comment]
I have solved this issue @vishanurag 

![Screenshot (186)](https://github.com/user-attachments/assets/3ede0fe3-33c6-4f45-ba8c-3dadd110f8fd)

**Comment by JOSHITHA6** [comment]
@vishanurag label under gssoc'24 extd and hacktoberfest.

**Comment by vishanurag** [comment]
Closed via #1027
