### ISSUE TITLE
Duplicate Drawing Options on Landing Page

### ISSUE THREAD

**Issue by divanshiii09** [vishanurag/Canvas-Editor#575]
### Description
The options for drawing tools—such as brush, clear canvas, eraser; 
                           text options—such as uppercase, lowercase, bold, italic, enter text; 
                           shapes—such as rectangle, circle, line, triangle, heart, square, pentagon, hexagon; and 
                           actions—such as save, clear, download
are displayed twice on the landing page. This duplication may cause confusion for users and disrupts the user interface.

---

### Steps to Reproduce
1. Navigate to the landing page.
2. Observe the drawing options presented.

---

### Expected Behavior
Each drawing option should only be displayed once to maintain clarity and enhance user experience.

---

### Suggested Improvement
- Remove the duplicate display of the drawing options to streamline the interface and improve usability.

---

### Screenshot
<img src="https://github.com/user-attachments/assets/b7a72fc4-cd0a-4a2c-a2ab-64e489962ada" alt="Duplicate Drawing Options" width="500" />

---

**Comment by divanshiii09** [comment]
@vishanurag I would love to work on this issue, please assign it to me

**Comment by vishanurag** [comment]
Issue already resolved

**Comment by divanshiii09** [comment]
okayy
