### ISSUE TITLE
Blog page search bar

### ISSUE THREAD

**Issue by saumyayadav25** [vishanurag/Canvas-Editor#603]
In-accurate text in search bar. it should be something like "find designs" or "search blogs"

<img width="1121" alt="Screenshot 2024-10-16 at 7 55 33 PM" src="https://github.com/user-attachments/assets/d2d9a367-ac41-4325-bd46-9fe203026372">

**Comment by arbazahmed07** [comment]
hey can you please assign me this @saumyayadav25
