### ISSUE TITLE
Fix Sign Up page

### ISSUE THREAD

**Issue by Son7c** [vishanurag/Canvas-Editor#639]
I'll fix this for you

Before
![Screenshot 2024-10-17 211818](https://github.com/user-attachments/assets/9cc1c0c9-6271-42d7-9552-6b8081fb7f3b)

After

https://github.com/user-attachments/assets/7e1c91ec-9ce0-4837-8a36-d0de1ce74cf7

@vishanurag Please assign this issue to me

**Comment by tulikaa25** [comment]
Please assign this issue to me @vishanurag

**Comment by Son7c** [comment]
@vishanurag Please assign this to me the issue is open since 2 days

**Comment by VanshGarg06** [comment]
Hi! I am eager to contribute towards this issue. Kindly assign this issue to me.

**Comment by VanshGarg06** [comment]
I think it does not matter that who raised the issue first. It totally depends on the maintainer that whom he has to assign it to as everybody wants to contribute in its own way. I am not doing this in the hunger of any swags and all just wanted to contribute to any thing/issue and any how. Even I can correct this whole website at once if the maintainer wants.

**Comment by Son7c** [comment]
> I think it does not matter that who raised the issue first. It totally depends on the maintainer that whom he has to assign it to as everybody wants to contribute in its own way. I am not doing this in the hunger of any swags and all just wanted to contribute to any thing/issue and any how. Even I can correct this whole website at once if the maintainer wants.

I am waiting fir this issue to be assigned to me from 2 days. I am also eager to contribute.
