### ISSUE TITLE
Font Uniformness

### ISSUE THREAD

**Issue by ShradhaSaxena23** [vishanurag/Canvas-Editor#643]
I have observed that font family used in the website is not uniform.

**Objective:**

Ensure a consistent font family is used across the website for a cohesive look.
Optimize font sizes to enhance readability and improve the overall visual appeal.

Please assign this issue with the label **hacktoberfest and gssoc ext 24**.

![Screenshot (182)](https://github.com/user-attachments/assets/71e11397-70f0-410e-ae43-d7535ecd4e23)

**Comment by VanshGarg06** [comment]
Hi! I am eager to contribute towards this issue. Kindly assign this issue to me.
