### ISSUE TITLE
🐛BUG : Contact Us page - Name field validation

### ISSUE THREAD

**Issue by akash70629** [vishanurag/Canvas-Editor#652]
### Description

The "Name" field on the **_Contact Us_** page should only accept alphabetical letters (a-z, A-Z). Currently, the field allows users to input symbols and special characters, which may lead to invalid or spam submissions.

### Steps to Reproduce

1. Go to  Contact Us page
2. Click on the Name field and type numbers and symbols.
3. See there is no error message.

### Expected Behavior

The "Name" field in the Contact Us Page should only accept alphabetical letters (a-z, A-Z).

### Actual Behavior

Currently, the field allows users to input symbols and special characters, which may lead to invalid or spam submissions.

### Screenshots

![image](https://github.com/user-attachments/assets/76c96c1b-1fa9-407b-8a35-2020117197b0)

### What browser are you seeing the problem on?

- [X] Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I want to work on this issue.

**Comment by tulikaa25** [comment]
Please assign this issue to me @vishanurag

**Comment by akash70629** [comment]
> Please assign this issue to me @vishanurag

Hey @tulikaa25, I've already submitted a PR for this issue 😕😕
