### ISSUE TITLE
FAQ additional home button

### ISSUE THREAD

**Issue by saumyayadav25** [vishanurag/Canvas-Editor#678]
Canvas title is getting hidden due to additional home button
<img width="1352" alt="Screenshot 2024-10-18 at 10 02 47 PM" src="https://github.com/user-attachments/assets/8a8a4f0e-5049-437b-8016-7e97da7e21be">

**Comment by arpit74170** [comment]
please assign this task to me, i will solve this issue

**Comment by saumyayadav25** [comment]
@vishanurag kindly review this issue.

**Comment by VanshGarg06** [comment]
Hi ! I am eager to contribute towards this issue. Kindly assign this issue to me, i will rectify the issue as soon as possible.
