### ISSUE TITLE
REVIEW page is unusable

### ISSUE THREAD

**Issue by 1ShahidBashir** [vishanurag/Canvas-Editor#686]
@vishanurag the review page of the website looks like this
![image](https://github.com/user-attachments/assets/663bacc7-3f64-4e8d-a0d7-a56e34faa843)
I want to make improvements in it

**Comment by 1ShahidBashir** [comment]
@vishanurag please assign this issue to me

**Comment by vishanurag** [comment]
@somyadipghosh Please review the issue and do the needful.

**Comment by somyadipghosh** [comment]
@1ShahidBashir i've assigned this issue
