### ISSUE TITLE
Contact us not visible in dark mode

### ISSUE THREAD

**Issue by KartikSaxena19** [vishanurag/Canvas-Editor#694]
As you can see the contact us is not visible in dark mode 
Please assign this issue to me under the tag of gssoc ext and hacktoberfest 
![Screenshot_2024-10-19-10-51-43-446_com android chrome](https://github.com/user-attachments/assets/87c75128-d594-442e-a8f8-f658cde27861)

**Comment by vishanurag** [comment]
Closed via #719
