### ISSUE TITLE
Add "back to top" button in all pages

### ISSUE THREAD

**Issue by swathivemula7** [vishanurag/Canvas-Editor#705]
For now, the "back to top" button is present only in home page, I would like to add it in all the other pages where it is missing.

@vishanurag Kindly assign me under the labels gssoc and hacktoberfest

**Comment by Son7c** [comment]
@somyadipghosh Can you please assign me this issue?

**Comment by swathivemula7** [comment]
@somyadipghosh You have assigned two members...but I raised the issue...kindly check...shall I start working on it?

**Comment by swathivemula7** [comment]
@somyadipghosh please add level label also

**Comment by somyadipghosh** [comment]
@swathivemula7 you can start working on it, i've messed up, sorry for the issues.
