### ISSUE TITLE
Optimize_Images_for_Better_Performance

### ISSUE THREAD

**Issue by smog-root** [vishanurag/Canvas-Editor#714]
We need to optimize images on our website to improve loading speed and overall performance. This includes compressing existing images and converting them to more efficient formats like WebP.

**Compress Images:**

Use tools like TinyPNG or ImageOptim to reduce the file size of current images without sacrificing quality.

**Convert to WebP Format:**

Change image formats from JPEG/PNG to WebP where appropriate to enhance performance.

**Enable Lazy Loading:**

Implement lazy loading for images to defer loading off-screen images until they are needed.

`<img src="image.jpg" alt="Description" loading="lazy">
`

**_Note:_** Assign me and add gssoc-ext with level3 (or) level2 and hacktober-accepted labels!

@vishanurag

**Comment by smog-root** [comment]
@somyadipghosh add level3 label!!!

**Comment by vishanurag** [comment]
Closed via #821
