### ISSUE TITLE
Change the position of nav bar and dark mode

### ISSUE THREAD

**Issue by Kajalmehta29** [vishanurag/Canvas-Editor#722]
Nav bar should be at the top and dark mode should be in nav bar.
I want to fix this issue.
<img width="1470" alt="Screenshot 2024-10-19 at 11 58 20 PM" src="https://github.com/user-attachments/assets/be248e5f-0614-4765-b105-0a6da291d873">

Please assign this issue to me under gssoc-extd and hacktoberfest.

**Comment by haseenpari** [comment]
Please assign this work to meee
