### ISSUE TITLE
Title Not Visible and Text of Contact Us

### ISSUE THREAD

**Issue by Kavish-Paraswar** [vishanurag/Canvas-Editor#731]
The title in not visible , alignment of the title should be changed .
![image](https://github.com/user-attachments/assets/a12714f0-ceeb-42c0-a984-efe417d18ef9)

The contact us is not visible , adding that
![image](https://github.com/user-attachments/assets/54362cf3-5409-4742-bc8c-7237f673b0df)

**Comment by Kavish-Paraswar** [comment]
![image](https://github.com/user-attachments/assets/8c933ad2-7d3c-4e1d-bddb-50b542d8e581)
@somyadipghosh  is anybody working for UI of index page

**Comment by Kavish-Paraswar** [comment]
this issue is resolved and pr is raised #

**Comment by vishanurag** [comment]
Closed via #939
