### ISSUE TITLE
I want to add brightness , saturation and blur section 

### ISSUE THREAD

**Issue by rounakdey6** [vishanurag/Canvas-Editor#74]
please assign this issue to me

**Comment by rounakdey6** [comment]
![image](https://github.com/user-attachments/assets/2788f6a9-1dbf-496a-89fd-e73072fc3342)
what should i do now ?

**Comment by rounakdey6** [comment]
![image](https://github.com/user-attachments/assets/2c066976-2c85-4556-9c2f-f2c827ca612d)
i added a section where ppl can add a picture also they want and set the brightness , saturation and blur also 
@vishanurag

**Comment by rounakdey6** [comment]
@vishanurag please tell me

**Comment by vishanurag** [comment]
> ![image](https://private-user-images.githubusercontent.com/98476572/373384295-2788f6a9-1dbf-496a-89fd-e73072fc3342.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwMTE4MzEsIm5iZiI6MTcyODAxMTUzMSwicGF0aCI6Ii85ODQ3NjU3Mi8zNzMzODQyOTUtMjc4OGY2YTktMWRiZi00OTZhLTg5ZmQtZTczMDcyZmMzMzQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDAzMTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MWU5MWUwOGRkYWFmMTg2NjQzMjEzNTkwYjA0NTIwYWM2NDNjNzUzYTVlZjA2YzY1MjcxNjFiMzJmY2RjNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.c9rETDR3GdeESBIdiscTRW3d6cL2Z8tnuJbN-zAEBfo) what should i do now ?

First of all, you need to fork this repo then you have to clone the forked repo not this one.
Then you can make changes in code and will be able to push the code to your forked repo. Then you can create a pr.

**Comment by rounakdey6** [comment]
@vishanurag and the changes that I have added , does it look good?

**Comment by rounakdey6** [comment]
![image](https://github.com/user-attachments/assets/5b2b827f-a729-48d3-bf80-bc6ff118fd38)
i didn't get it

**Comment by rounakdey6** [comment]
@vishanurag please help me out
