### ISSUE TITLE
Redesigning about us page

### ISSUE THREAD

**Issue by Son7c** [vishanurag/Canvas-Editor#748]
I would redesign the entire about us page and make it very attractive

https://github.com/user-attachments/assets/e35ef217-18b9-4cf5-b427-2739bd258769

**Comment by Son7c** [comment]
@vishanurag @somyadipghosh Please assign me this issue

**Comment by ishivansmishra** [comment]
@somyadipghosh Please assign this issue to me

**Comment by Son7c** [comment]
> @somyadipghosh Please assign this issue to me
> 

I already made a PR
