### ISSUE TITLE
Blog cards are not mobile responsive 

### ISSUE THREAD

**Issue by swathivemula7** [vishanurag/Canvas-Editor#751]
In the blog page, there are cards which are not responsive for the mobile version..
They are poorly aligned...and text is out of box..I would like to fix this..

![IMG_20241020_162122](https://github.com/user-attachments/assets/3ea5b7ab-866d-4eaa-b231-c6e2336efa4e)

@vishanurag @somyadipghosh Kindly assign me this issue under gssoc and hacktoberfest labels

**Comment by swathivemula7** [comment]
@somyadipghosh The set of blog cards(6 cards) I mentioned above are repeated twice..One set of cards with blue background and the same set of cards with images...i have added the images of both...Should I remove one set of cards to reduce code redundancy...
![Capturedmef](https://github.com/user-attachments/assets/f301f5c5-40ae-4b3a-909d-1d123c12aa1c)
![Capturemfkv](https://github.com/user-attachments/assets/eadc9bc3-30e9-4f95-bff9-b0a794897f0d)

**Comment by swathivemula7** [comment]
@somyadipghosh At first, I found that the blue cards were not aligned in the mobile version. So I raised the issue, but now the same set of cards are repeated.

**Comment by somyadipghosh** [comment]
@swathivemula7 sure, you can remove one set of cards, and you can also remove the cards which are repeated.

**Comment by swathivemula7** [comment]
> @swathivemula7 sure, you can remove one set of cards, and you can also remove the cards which are repeated.

Ok, I will remove the set of cards with blue background
