### ISSUE TITLE
Automated updation of project structure in the readme file with workflow and python script 

### ISSUE THREAD

**Issue by J-B-Mugundh** [vishanurag/Canvas-Editor#762]
Sample: 

![image](https://github.com/user-attachments/assets/1479e5a9-8032-41cd-9a28-93a73908571b)

**Comment by J-B-Mugundh** [comment]
@somyadipghosh Please assign me this issue.

**Comment by J-B-Mugundh** [comment]
@somyadipghosh Bro, Shouldn't this fetch atleast level 2? I could see other repos have given level 2 and level 3 for this. 

Sample: 

![image](https://github.com/user-attachments/assets/7c5d9068-8617-4c95-8b8a-db2cabeea556)

**Comment by somyadipghosh** [comment]
@J-B-Mugundh lvl 2 given
