### ISSUE TITLE
Redesigning of buttons in homepage 

### ISSUE THREAD

**Issue by Subashree-selvaraj** [vishanurag/Canvas-Editor#772]
Description :
The current button design may not fully utilize modern design practices. A redesign will make the buttons more visually appealing, accessible, and user-friendly, thereby improving interaction and engagement on the homepage.

**Comment by akilesh26** [comment]
Hi, i would like to work on this issue.

**Comment by Subashree-selvaraj** [comment]
@somyadipghosh Raised PR. Kindly check it! #871
