### ISSUE TITLE
[⭐FEATURE] Add a ChatBot Assistant

### ISSUE THREAD

**Issue by Subhajit-2023-44** [vishanurag/Canvas-Editor#780]
I want to add a ChatBot Assistant..

@vishanurag  please assign me this task.

![Screenshot 2024-10-20 210028](https://github.com/user-attachments/assets/8dbf7549-89e9-4c7c-8d00-a7f3eb69f104)

**Comment by Subhajit-2023-44** [comment]
@vishanurag

**Comment by vishanurag** [comment]
chatbot is already present in the website.
