### ISSUE TITLE
dark mode toggle UI for HOME page

### ISSUE THREAD

**Issue by NIKITABARANWAL890** [vishanurag/Canvas-Editor#791]
If my issue no.#733 seems fine to you
then to proceed further after that, i want to imrpove the design for the dark mode toggle as well

@somyadipghosh kindly assign this issue to me with a higher level, i genuinelly want to work for this imrpovement.

**Comment by ishivansmishra** [comment]
@somyadipghosh Please assign me this issue

**Comment by vishanurag** [comment]
Closed via #808
