### ISSUE TITLE
Enhancing Readme.md 

### ISSUE THREAD

**Issue by neeru24** [vishanurag/Canvas-Editor#8]
Hi,

I’ve been exploring the project and appreciate the work you’ve done so far. I’d like to propose an update to the README.md file. Here are a few ideas I have in mind:

I want to add some animations (icons), change the alignment of text and few more changes...

I believe these updates could enhance user understanding and engagement with the project. If you're open to it, I’d love to contribute.

I’m committed to continually improving the quality of our documentation.

Thank you!

**Comment by vishanurag** [comment]
I'm assigning this issue to you. Go ahead.

**Comment by neeru24** [comment]
> I'm assigning this issue to you. Go ahead.

I've made the changes. Kindly check it out 👍
