### ISSUE TITLE
Sign-up page goes OFF Theme

### ISSUE THREAD

**Issue by NIKITABARANWAL890** [vishanurag/Canvas-Editor#809]
![Screenshot 2024-10-21 112936](https://github.com/user-attachments/assets/58f691ef-c959-45fe-abb1-be59cd1a8942)

Sign-up page goes off from the CANVAS-EDITOR's color theme
and this leads to a poor designing for a color play website.

@somyadipghosh kindly assign this issue to me under GSSOC'24 ext. I'm willing to work on it.

**Comment by vishanurag** [comment]
closed via #842
