### ISSUE TITLE
Mistek in code writing

### ISSUE THREAD

**Issue by PATILYASHH** [vishanurag/Canvas-Editor#812]
## mistake in code writing 

<img width="871" alt="image" src="https://github.com/user-attachments/assets/b96fb92f-1dcb-4568-a2ef-41ac120b57d3">

--> is accidently placed

**Comment by PATILYASHH** [comment]
please assign me this issue

**Comment by PATILYASHH** [comment]
@somyadipghosh please check the PR

**Comment by HarshKumar1121** [comment]
@PATILYASHH  would you assign this issue to me  i will do my best to solve this issue .
