### ISSUE TITLE
Footer Needs UI/UX Improvements for Better Spacing, Alignment, and Visual Consistency

### ISSUE THREAD

**Issue by amanver45** [vishanurag/Canvas-Editor#830]
The current footer design has some usability and visual hierarchy issues that can be enhanced to improve the overall user experience and appearance. The spacing, alignment, and color scheme of certain elements like the social media icons, visitor counter, and copyright text could benefit from refinement. Here are the details of the issues and suggested improvements:Issues Identified:

Spacing and Alignment:

The social media icons are closely packed together, making the footer feel cramped.
The visitor counter and social media icons do not seem evenly aligned, and the overall layout feels inconsistent.
There's little padding between the social icons and the copyright text, causing visual clutter.
Visual Hierarchy:

The visitor counter is too prominent for its purpose. It draws too much attention compared to more important elements.
The font size and color contrast for the copyright section could be improved for better readability against the dark background.
Social Media Icons:

The icons lack hover effects, which reduces interactivity and visual feedback for users.
The current color scheme of the icons is inconsistent. Some icons use brand colors, while others don't.
Back-to-Top Button:

The "Back to Top" button’s design could be more aligned with the site’s theme, and it feels disconnected from the rest of the footer in terms of styling.
Suggested Improvements:

Improve Spacing and Alignment:

Increase the space between social media icons and ensure they are evenly distributed.
Add more padding between the icons and the copyright text for better separation.
Center-align the visitor counter and social icons for a more symmetrical layout.

![Screenshot 2024-10-21 202745](https://github.com/user-attachments/assets/50169c26-9955-4b7b-acde-abcd704d8259)

**Comment by aahanajena** [comment]
i would like to work on this issue. pls assign me the work
