### ISSUE TITLE
Navigation Bar Visual Issues - Spacing and Alignment Fixes

### ISSUE THREAD

**Issue by veepanshu-kasana** [vishanurag/Canvas-Editor#833]
I noticed several visual issues with the current navbar that affect user experience:
1. Spacing inconsistencies between nav items
2. Alignment problems with navbar elements
3. Elements overlapping each other on mobile devices

![Screenshot_2024-10-21_20-57-11](https://github.com/user-attachments/assets/89d74dfb-d74f-4801-b6aa-3037a2dda61c)
![Screenshot_2024-10-21_20-56-37](https://github.com/user-attachments/assets/cb73a608-2dff-4b79-a394-f50f5e7ad953)

@somyadipghosh kindly assign this issue to me under GSSOC'24 ext. I'm willing to work on it.

**Comment by praneethaBrindavanam** [comment]
![Screenshot 2024-10-23 151448](https://github.com/user-attachments/assets/5f7cf64d-a0a6-4c29-a084-bf32298f0bbb)
@somyadipghosh i would like to change the nav bar 
i will provide spacing between the nav bar 
please assign this issue!
