### ISSUE TITLE
 Contact Us section is not responsive

### ISSUE THREAD

**Issue by KAJAL7764** [vishanurag/Canvas-Editor#859]
Issue 1:
  Submit button on the contact us form doesn't resize correctly on smaller size screen.
Issue 2:
   The top margin of the contact section not appears intractive.

![js1](https://github.com/user-attachments/assets/943e5696-f99d-49dd-ae50-c8dad4f84827)
![js2](https://github.com/user-attachments/assets/f8fc4956-eeeb-4094-8783-22cfd9d431d9)
 

Could you please assign me this project.

**Comment by ChathuraHasanga44** [comment]
i want to work with this issue.

**Comment by vishanurag** [comment]
The new UI looks completely different from the earlier ui
