### ISSUE TITLE
Improve Text Visibility for "Contact Us" Section

### ISSUE THREAD

**Issue by Poushmita** [vishanurag/Canvas-Editor#887]
## Description: 
The "Contact Us" text on the website is currently not properly visible due to insufficient contrast against the background. This affects readability and user experience, especially for users with visual impairments. It is recommended to adjust the text colour, apply a shadow effect, or change the background to enhance visibility. Additionally, ensuring accessibility standards for colour contrast will improve overall usability.

## Screenshot
<img width="940" alt="1" src="https://github.com/user-attachments/assets/7ccf41de-d300-48e1-94de-c9608cd45681">

## Proposed Solution:
- Increase the contrast between the "Contact Us" text and the background by using a brighter or more prominent colour.
- Apply text-shadow to make the text stand out better.
- Consider changing the background colour or adding a semi-transparent overlay to ensure better visibility.

**Comment by ChathuraHasanga44** [comment]
i want to work with this issue. aasign me

**Comment by Poushmita** [comment]
it is done already
