### ISSUE TITLE
BUG Fix the issue of the main 

### ISSUE THREAD

**Issue by fluid111** [vishanurag/Canvas-Editor#907]
Currently the project is showing the code which is supposed to display the content 
![Screenshot 2024-10-24 174943](https://github.com/user-attachments/assets/6a571227-a43c-4b9e-821f-5a6e25b4c6e2)

**Comment by Bhupendrakumar20** [comment]
@vishanurag kindly assigned this issue to me. surely I will solve it

**Comment by vishanurag** [comment]
Go ahead, but remember code is visible in footer this time.
