### ISSUE TITLE
Fix the "Welcome to the Canvas Editor!" section

### ISSUE THREAD

**Issue by Aditya620321** [vishanurag/Canvas-Editor#917]
Welcome to the Canvas Editor! it is written two times.
![image](https://github.com/user-attachments/assets/02f7070a-c359-4d5d-a833-354fefd4c6fc)

**Comment by Aditya620321** [comment]
can you please assign me so i can fix it.
@vishanurag

**Comment by vishanurag** [comment]
issue already fixed
