### ISSUE TITLE
# Adding Custom Cursor effect 

### ISSUE THREAD

**Issue by AnujShrivastava01** [vishanurag/Canvas-Editor#93]
Step 1: CSS for Custom Cursor
Step 2: HTML Structure
Step 3: JavaScript for Additional Effects

# Adding special effect and making Custom designed Cursor for more attarctive UI
 

https://github.com/user-attachments/assets/625b7e77-1a1b-4e1a-a7cc-7791a19ed038

Please Assign this to me .
Thankyou !

**Comment by vishanurag** [comment]
Closed by #130
