### ISSUE TITLE
Logo not visible in navbar in review page

### ISSUE THREAD

**Issue by Arveti-likhitha** [vishanurag/Canvas-Editor#931]
The website logo is not visible in the review page and i would like to add the logo and make sure it navigates the user to home page when clicked.

![image](https://github.com/user-attachments/assets/99452775-a4fe-40fb-9529-d7f5563ec923)

Please assign this to me with the labels: hacktoberfest-accepted, gssoc-ext

**Comment by joshi-1245** [comment]
i would like to work on this project please assign to me
