### ISSUE TITLE
 add scroll up button in about us page & Make the Scroll up button to the Right side and increase the size of it-I really like your project

### ISSUE THREAD

**Issue by sambedan1** [vishanurag/Canvas-Editor#946]

**Comment by vishanurag** [comment]
Go ahead

**Comment by sambedan1** [comment]
![Screenshot 2024-10-26 205222](https://github.com/user-attachments/assets/bb74ae39-97ba-41a7-9364-d417e163c890)

**Comment by sambedan1** [comment]
i added a scroll up button in the about us page and also increase the size of scroll up button -please check my work and tell me if any modified needed! Thank you
