### ISSUE TITLE
Correct the  Orientation of Text Boxes, Social Media Icons, and Feature Buttons

### ISSUE THREAD

**Issue by charmi2109** [vishanurag/Canvas-Editor#957]
I identified an issue with the improper orientation of text boxes, social media icons, and other feature buttons within the interface. The current layout affects usability and visual appeal, leading to a disjointed user experience.

![image](https://github.com/user-attachments/assets/3d565c4e-5fb1-4d67-bf99-7804a6298bcc)
relevant tags: UI , feature, gssoc-ext

SOLUTION:
Text Box Alignment
Social Media Icons Positioning
Feature Buttons Arrangement
Please assign me this issue @vishanurag .

**Comment by vishanurag** [comment]
similar issue is already assigned to someone else
