### ISSUE TITLE
Dark mode button functionality 

### ISSUE THREAD

**Issue by Prachiikhar25** [vishanurag/Canvas-Editor#960]
Hello! there is need for some modifications in display 
1. Converting Social media icons from column to row

![{41CA2D89-463E-4572-842D-8DA58E15DAE9}](https://github.com/user-attachments/assets/23ea7900-4e08-4e13-b0bc-6c24c8743a85)
 
2. Secondly, modifying the space for textboxes.

![{48DB0396-AD53-4BD4-88CB-2C401E299A0E}](https://github.com/user-attachments/assets/8bc62b18-2c8f-45de-8fdf-c69a698cbb22)

3. Enhancing the space between textboxes

![{7F7B8B9E-E924-44F8-A70E-1A025CE73ABA}](https://github.com/user-attachments/assets/81fe3999-34a5-41f9-9ebc-12406ed10050)

4. Shifting the Thank You section in center
![image](https://github.com/user-attachments/assets/1507f0d1-37e8-4dcf-b5ac-66626e6b8bad)

Thanks for your patience!

**Comment by vishanurag** [comment]
Closed via #991
