### ISSUE TITLE
BUG in the "Your Message" section.

### ISSUE THREAD

**Issue by rees8** [vishanurag/Canvas-Editor#961]
![image](https://github.com/user-attachments/assets/9914c9f0-1145-4c2d-b47e-4fa27e72a6d6)

This message should ideally be displayed on clicking the "Submit" button, but it is being displayed by default on the home page.

Solution fix: By applying the "onclick" functionality on the submit button, we can have the message being displayed only after the button has been clicked. Also, the "Close" button seems irrelevant since there is no redirection of page taking place.

I would like to work on this task @vishanurag

**Comment by vishanurag** [comment]
similar issue is already assigned
