### ISSUE TITLE
{BUG}: REMOVE EXTRA UI

### ISSUE THREAD

**Issue by Darshan3690** [vishanurag/Canvas-Editor#973]
HI , @vishanurag 
  1) ![WhatsApp Image 2024-10-27 at 09 37 21_032a4bbf](https://github.com/user-attachments/assets/c04a7a4e-97d2-46b6-b2cb-ae54162911f7)
  Currently your code show this type extra icon. i want to work on this.
2)
![WhatsApp Image 2024-10-27 at 09 35 35_57555529](https://github.com/user-attachments/assets/b5974edc-6323-4425-a27a-cb344e8b8c7f)
and in footer section display some extra code. i want work on this.
Under Gssoc'24. please assign me for this issuse.

**Comment by vishanurag** [comment]
The similar issues are already assigned or resolved.
