### ISSUE TITLE
Add content to CONTRIBUTING.md

### ISSUE THREAD

**Issue by Devaki01** [vishanurag/Canvas-Editor#98]
**Issue Description**
Contributing.md file is empty right now.

**Suggested Change**
I would love to contribute by adding relevant content to CONTRIBUTING.md which includes guidelines for reporting issues, making feature requests, setting up project, committing changes, submitting code, updating documentation, and following the pull request process.

**Rationale**
A well-structured CONTRIBUTING.md would ensure consistency in code quality and collaboration and help beginners contribute better.

Please assign me this issue under ggsoc'24 extd and hacktoberfest.

**Comment by Devaki01** [comment]
Thank you assigning it to me. Will complete it by today.

**Comment by vishanurag** [comment]
Closed by #160
