### ISSUE TITLE
BUG: Image is not visible in About section

### ISSUE THREAD

**Issue by swati-204** [vishanurag/Canvas-Editor#981]
There is an issue where the image in the About section is not displaying as expected. This affects the visual presentation of the page and may lead to confusion for users.

![Video Screen1730013376256](https://github.com/user-attachments/assets/321daf13-2f5d-498a-b52d-a78fa4234a74)

@vishanurag   can you assign this to me?

**Comment by vishanurag** [comment]
Issue is already resolved
