### ISSUE TITLE
Improve the whole ui of the website 

### ISSUE THREAD

**Issue by HimangshuSharma01** [vishanurag/Canvas-Editor#988]
i can show you the sample of how it will look

**Comment by vishanurag** [comment]
> i can show you the sample of how it will look

yes please.

**Comment by HimangshuSharma01** [comment]
https://github.com/user-attachments/assets/02a2a2e4-fb9f-4c4b-a8e1-d2026fb08338

**Comment by vishanurag** [comment]
> Untitled.video.-.Made.with.Clipchamp.12.mp4 
> @vishanurag Kindly tell me if this will work there are several functions in the current one which doesn't work I have fixed them..

I have assigned this issue to you. But remember that navbar, footer and other options should be present.

**Comment by HimangshuSharma01** [comment]
> > Untitled.video.-.Made.with.Clipchamp.12.mp4 
> > @vishanurag Kindly tell me if this will work there are several functions in the current one which doesn't work I have fixed them..
> 
> I have assigned this issue to you. But remember that navbar, footer and other options should be present.

Yes for sure don't worry I will finish this by tonight I'm in college right now
