### ISSUE TITLE
Fix About Page Layout: Heading and Description Misaligned

### ISSUE THREAD

**Issue by Raj-banerjee25** [vishanurag/Canvas-Editor#997]
On the About page, the heading is on the far left, and the description is centered but stretches too far to the right. This layout looks unbalanced and is hard to read.

Expected Result:
Heading and description should be close together and centered for a clean look.

![edit2](https://github.com/user-attachments/assets/615be66b-eed0-4e8a-bb1b-69f9477a9752)

**Comment by vishanurag** [comment]
Issue already resolved
